name: FluxaApple
options:
  xcodeVersion: "16.4"
  deploymentTarget:
    iOS: "18.5"
    tvOS: "17.0"
settings:
  base:
    GENERATE_INFOPLIST_FILE: YES
targets:
  FluxaIos:
    type: application
    platform: iOS
    sources:
      - path: Shared
      - path: iOS
      - path: Generated/FluxaRustCore.swift
    resources:
      - path: ../core/src/androidMain/assets/i18n
    dependencies:
      - framework: UIKit.framework
      - framework: Generated/FluxaRustCore.xcframework
    preBuildScripts:
      - name: Build Fluxa Rust Core
        script: scripts/build-rust-core-xcframework.sh
        basedOnDependencyAnalysis: false
      - name: Build FluxaShared
        script: ../gradlew -p .. :shared:embedAndSignAppleFrameworkForXcode
        basedOnDependencyAnalysis: false
  FluxaTvos:
    type: application
    platform: tvOS
    sources:
      - path: tvOS
      - path: Generated/FluxaRustCore.swift
    resources:
      - path: ../core/src/androidMain/assets/i18n
    dependencies:
      - framework: Generated/FluxaRustCore.xcframework
    preBuildScripts:
      - name: Build Fluxa Rust Core
        script: scripts/build-rust-core-xcframework.sh
        basedOnDependencyAnalysis: false
      - name: Build FluxaCore
        script: ../gradlew -p .. :core:embedAndSignAppleFrameworkForXcode
        basedOnDependencyAnalysis: false
