name: FluxaApple
options:
  xcodeVersion: "16.4"
  deploymentTarget:
    iOS: "18.0"
    tvOS: "17.0"
settings:
  base:
    GENERATE_INFOPLIST_FILE: YES
targets:
  FluxaIos:
    type: application
    platform: iOS
    sources:
      - path: Shared
      - path: iOS
    resources:
      - path: ../core/src/androidMain/assets/i18n
    preBuildScripts:
      - name: Build FluxaShared
        script: ../gradlew -p .. :shared:embedAndSignAppleFrameworkForXcode
        basedOnDependencyAnalysis: false
  FluxaTvos:
    type: application
    platform: tvOS
    sources:
      - path: tvOS
    resources:
      - path: ../core/src/androidMain/assets/i18n
    preBuildScripts:
      - name: Build FluxaCore
        script: ../gradlew -p .. :core:embedAndSignAppleFrameworkForXcode
        basedOnDependencyAnalysis: false
