import type React from 'react';

export const NAV_RAIL_WIDTH = 6.5;
export const PX = 58;

export const styles: Record<string, React.CSSProperties> = {
  screen: {
    background: 'var(--fluxa-background)',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    paddingLeft: `${NAV_RAIL_WIDTH}rem`,
  },
  header: { display: 'flex', alignItems: 'center', gap: '1.5rem', padding: '2.5rem 3.625rem', flexShrink: 0 },
  controls: { marginLeft: 'auto', display: 'flex', alignItems: 'center', gap: '0.625rem' },
  bulkToggle: {
    height: '2.25rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.4375rem',
    padding: '0 0.75rem',
    border: '1px solid var(--fluxa-border)',
    borderRadius: '0.5rem',
    fontSize: '0.8125rem',
    fontWeight: 800,
    cursor: 'pointer',
  },
  searchWrap: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.4375rem',
    height: '2.25rem',
    padding: '0 0.75rem',
    width: '13.75rem',
    background: 'var(--fluxa-fill)',
    border: '1px solid var(--fluxa-border)',
    borderRadius: '0.5rem',
  },
  searchInput: {
    flex: 1,
    minWidth: 0,
    background: 'none',
    border: 'none',
    outline: 'none',
    color: 'var(--fluxa-text-primary)',
    fontSize: '0.8125rem',
    fontWeight: 600,
  },
  collectionsScroll: { flex: 1, minHeight: 0, overflowY: 'auto', paddingBottom: '5rem' },
  title: { color: 'var(--fluxa-text-primary)', fontSize: '2rem', fontWeight: 900, margin: '0 0 0.25rem', letterSpacing: '0.125rem' },
  subtitle: { color: 'var(--fluxa-text-muted)', fontSize: '0.875rem', margin: 0, lineHeight: 1.4 },
  tabRow: { display: 'flex', alignItems: 'center', gap: '0.625rem', paddingLeft: PX, paddingRight: PX, flexShrink: 0, flexWrap: 'wrap' },
  bulkBar: {
    margin: '0.875rem 3.625rem 0',
    minHeight: '2.75rem',
    padding: '0.4375rem 0.5rem',
    borderRadius: '0.625rem',
    border: '1px solid var(--fluxa-border)',
    background: 'var(--fluxa-fill)',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    flexShrink: 0,
  },
  bulkCount: { color: 'var(--fluxa-text-secondary)', fontSize: '0.8125rem', fontWeight: 800 },
  bulkBtn: {
    height: '1.875rem',
    padding: '0 0.625rem',
    borderRadius: '0.4375rem',
    border: '1px solid var(--fluxa-border)',
    background: 'var(--fluxa-fill-hover)',
    color: 'var(--fluxa-text-primary)',
    fontSize: '0.75rem',
    fontWeight: 800,
    cursor: 'pointer',
  },
  bulkDangerBtn: {
    height: '1.875rem',
    padding: '0 0.625rem',
    borderRadius: '0.4375rem',
    border: '1px solid rgba(255,80,80,0.22)',
    background: 'rgba(255,80,80,0.14)',
    color: 'var(--fluxa-text-primary)',
    fontSize: '0.75rem',
    fontWeight: 800,
    cursor: 'pointer',
  },
  bulkGhostBtn: {
    height: '1.875rem',
    padding: '0 0.625rem',
    borderRadius: '0.4375rem',
    border: '1px solid var(--fluxa-border)',
    background: 'transparent',
    color: 'var(--fluxa-text-secondary)',
    fontSize: '0.75rem',
    fontWeight: 800,
    cursor: 'pointer',
  },
  bulkIconBtn: {
    width: '1.875rem',
    height: '1.875rem',
    borderRadius: '0.4375rem',
    border: 'none',
    background: 'transparent',
    color: 'var(--fluxa-text-secondary)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
  },
  errorBanner: {
    margin: '0.875rem 3.625rem 0',
    padding: '0.75rem 0.875rem',
    borderRadius: '0.625rem',
    border: '1px solid var(--fluxa-border)',
    background: 'var(--fluxa-fill)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '1rem',
    flexShrink: 0,
  },
  errorTitle: { color: 'var(--fluxa-text-primary)', fontSize: '0.8125rem', fontWeight: 850, margin: '0 0 0.1875rem' },
  errorText: {
    color: 'rgba(255,255,255,0.52)',
    fontSize: '0.75rem',
    fontWeight: 600,
    margin: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  errorBtn: {
    height: '2rem',
    padding: '0 0.75rem',
    borderRadius: '62.4375rem',
    border: '1px solid rgba(255,255,255,0.14)',
    background: '#FFFFFF',
    color: '#000000',
    fontSize: '0.75rem',
    fontWeight: 850,
    cursor: 'pointer',
    flexShrink: 0,
  },
  empty: { display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', paddingTop: '5rem', gap: '0.625rem' },
  emptyTitle: { color: '#FFFFFF', fontSize: '1.25rem', fontWeight: 700, margin: 0 },
  emptyHint: { color: 'rgba(255,255,255,0.4)', fontSize: '0.875rem', margin: 0, textAlign: 'center', maxWidth: '20rem', lineHeight: 1.5 },
  historyScroll: { flex: 1, overflowY: 'auto', padding: '0.625rem 3.625rem 5rem', display: 'flex', flexDirection: 'column', gap: '0.5rem' },
  historyRow: {
    width: '100%',
    minHeight: '4.75rem',
    border: '1px solid rgba(255,255,255,0.08)',
    background: 'rgba(255,255,255,0.035)',
    borderRadius: '0.625rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
    padding: '0.625rem 0.75rem',
    cursor: 'pointer',
    textAlign: 'left',
  },
  historyDate: { width: '2.75rem', display: 'flex', flexDirection: 'column', alignItems: 'center', flexShrink: 0 },
  historyDay: { color: '#FFFFFF', fontSize: '1.125rem', fontWeight: 900, lineHeight: '1.25rem' },
  historyMonth: { color: 'rgba(255,255,255,0.42)', fontSize: '0.6875rem', fontWeight: 800, textTransform: 'uppercase' },
  historyPoster: { width: '2.375rem', height: '3.5rem', objectFit: 'cover', borderRadius: '0.375rem', flexShrink: 0 },
  historyInfo: { flex: 1, minWidth: 0 },
  historyTitle: {
    color: '#FFFFFF',
    fontSize: '0.9375rem',
    fontWeight: 850,
    margin: '0 0 0.3125rem',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  historyMeta: { color: 'rgba(255,255,255,0.48)', fontSize: '0.75rem', fontWeight: 650, margin: 0 },
  historyTime: { color: 'rgba(255,255,255,0.38)', fontSize: '0.75rem', fontWeight: 750, flexShrink: 0 },
  historyProgressTrack: {
    width: '10rem',
    maxWidth: '100%',
    height: '0.25rem',
    borderRadius: '62.4375rem',
    background: 'rgba(255,255,255,0.1)',
    marginTop: '0.5625rem',
    overflow: 'hidden',
  },
  historyProgressFill: { height: '100%', borderRadius: '62.4375rem', background: 'var(--primary-accent-color)' },
};
