import type React from 'react';

export const NAV_RAIL_WIDTH = 6.5;

export const styles: Record<string, React.CSSProperties> = {
  screen: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    background: 'var(--fluxa-background)',
    overflow: 'hidden',
  },
  topBar: {
    padding: '1.5rem 2rem 1rem',
    flexShrink: 0,
  },
  searchBox: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
    height: '3.25rem',
    background: 'var(--fluxa-fill)',
    border: '1px solid var(--fluxa-border)',
    borderRadius: '0.875rem',
    padding: '0 1rem',
  },
  input: {
    flex: 1,
    background: 'transparent',
    border: 'none',
    outline: 'none',
    color: 'var(--fluxa-text-primary)',
    fontSize: '1rem',
    fontWeight: 600,
  },
  clearBtn: {
    width: '1.75rem',
    height: '1.75rem',
    background: 'transparent',
    border: 'none',
    borderRadius: '50%',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    padding: 0,
  },
  content: {
    flex: 1,
    overflowY: 'auto',
    padding: `2.125rem 2.25rem 2.75rem ${NAV_RAIL_WIDTH + 2.625}rem`,
    scrollbarWidth: 'none',
  },
  header: {
    marginBottom: '1.375rem',
  },
  backBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.4375rem',
    height: '2.125rem',
    padding: '0 0.75rem',
    borderRadius: '62.4375rem',
    border: '1px solid var(--fluxa-border)',
    background: 'var(--fluxa-fill)',
    color: 'var(--fluxa-text-secondary)',
    fontSize: '0.75rem',
    fontWeight: 750,
    marginBottom: '1.125rem',
  },
  eyebrow: {
    color: 'var(--fluxa-text-faint)',
    fontSize: '0.75rem',
    fontWeight: 800,
    margin: '0 0 0.375rem',
    textTransform: 'uppercase',
    letterSpacing: '0.05rem',
  },
  title: {
    color: 'var(--fluxa-text-primary)',
    fontSize: '2.125rem',
    lineHeight: '2.4375rem',
    fontWeight: 900,
    margin: 0,
  },
  subtitle: {
    color: 'var(--fluxa-text-muted)',
    fontSize: '0.8125rem',
    fontWeight: 600,
    margin: '0.5rem 0 0',
  },
  typeRow: {
    display: 'flex',
    gap: '0.5rem',
    marginBottom: '1.75rem',
    flexWrap: 'wrap',
  },
  sectionLabel: {
    color: 'var(--fluxa-text-muted)',
    fontSize: '0.8125rem',
    fontWeight: 700,
    margin: '0 0 0.875rem',
    textTransform: 'uppercase',
    letterSpacing: '0.0313rem',
  },
  sectionHeaderRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '1rem',
    marginBottom: '0.875rem',
  },
  clearRecentBtn: {
    height: '1.75rem',
    padding: '0 0.625rem',
    border: '1px solid var(--fluxa-border)',
    background: 'var(--fluxa-background-elevated)',
    color: 'var(--fluxa-text-secondary)',
    borderRadius: '62.4375rem',
    fontSize: '0.75rem',
    fontWeight: 700,
    cursor: 'pointer',
  },
  recentGrid: {
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: '0.625rem',
    marginBottom: '2rem',
  },
  recentChip: {
    height: '2.375rem',
    display: 'flex',
    alignItems: 'center',
    border: '1px solid var(--fluxa-border)',
    borderRadius: '62.4375rem',
    transition: 'background 0.15s, border-color 0.15s',
    maxWidth: '17.5rem',
  },
  recentChipMain: {
    minWidth: 0,
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    padding: '0 0.5rem 0 0.8125rem',
    background: 'transparent',
    border: 'none',
    color: 'var(--fluxa-text-primary)',
    cursor: 'pointer',
  },
  recentChipText: {
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontSize: '0.8125rem',
    fontWeight: 700,
  },
  recentChipRemove: {
    width: '1.875rem',
    height: '1.875rem',
    marginRight: '0.25rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: 'none',
    borderRadius: '50%',
    background: 'transparent',
    color: 'var(--fluxa-text-faint)',
    cursor: 'pointer',
    flexShrink: 0,
  },
  genreGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(8.75rem, 1fr))',
    gap: '0.625rem',
    marginBottom: '2rem',
  },
  resultList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.5rem',
  },
  categoryList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.25rem',
    paddingBottom: '2.25rem',
  },
  category: {
    paddingTop: '0.75rem',
  },
  categoryTitle: {
    color: 'var(--fluxa-text-primary)',
    fontSize: '1.25rem',
    fontWeight: 800,
    margin: '0 0 0.75rem',
  },
  categoryScroll: {
    display: 'flex',
    gap: '0.875rem',
    overflowX: 'auto',
    overflowY: 'visible',
    padding: '0.5rem 2.25rem 1.75rem 0',
    scrollbarWidth: 'none',
  },
  skeletonTitle: {
    height: '1.25rem',
    borderRadius: '0.375rem',
    background: 'var(--fluxa-fill)',
    marginBottom: '0.875rem',
    animation: 'pulse 1.6s ease-in-out infinite',
  },
  skeletonCard: {
    width: '8.25rem',
    height: '12.375rem',
    borderRadius: '0.75rem',
    background: 'var(--fluxa-background-elevated)',
    flexShrink: 0,
    animation: 'pulse 1.6s ease-in-out infinite',
  },
  emptyState: {
    paddingTop: '2.5rem',
  },
  emptyTitle: {
    color: 'var(--fluxa-text-primary)',
    fontSize: '1.125rem',
    fontWeight: 700,
    margin: '0 0 0.375rem',
  },
  emptyHint: {
    color: 'var(--fluxa-text-muted)',
    fontSize: '0.875rem',
    margin: 0,
  },
  retryBtn: {
    height: '2.25rem',
    marginTop: '1rem',
    padding: '0 0.875rem',
    borderRadius: '62.4375rem',
    border: '1px solid var(--fluxa-border-strong)',
    background: 'var(--fluxa-text-primary)',
    color: 'var(--fluxa-background)',
    fontSize: '0.8125rem',
    fontWeight: 800,
    cursor: 'pointer',
  },
};
