// Generated by scripts/generate-headless-contracts.mjs — do not edit.
enum FluxaHeadlessEffectType {
    static let clearPlaybackProgress = "clearPlaybackProgress"
    static let enqueueOfflineDownload = "enqueueOfflineDownload"
    static let enqueueTraktScrobble = "enqueueTraktScrobble"
    static let exchangeAuthCode = "exchangeAuthCode"
    static let executePlugin = "executePlugin"
    static let fetchAddonManifest = "fetchAddonManifest"
    static let fetchAddonResource = "fetchAddonResource"
    static let fetchCatalogPage = "fetchCatalogPage"
    static let fetchDiscoverPage = "fetchDiscoverPage"
    static let fetchDetailSecondary = "fetchDetailSecondary"
    static let fetchDetailStreams = "fetchDetailStreams"
    static let fetchIntroSegments = "fetchIntroSegments"
    static let fetchMetaDetail = "fetchMetaDetail"
    static let fetchMetaDetailLookup = "fetchMetaDetailLookup"
    static let fetchPluginManifest = "fetchPluginManifest"
    static let fetchSeasonEpisodes = "fetchSeasonEpisodes"
    static let fetchSubtitles = "fetchSubtitles"
    static let fetchYoutubeTrailerPlayer = "fetchYoutubeTrailerPlayer"
    static let fetchYoutubeTrailerPlayerScript = "fetchYoutubeTrailerPlayerScript"
    static let fetchYoutubeTrailerWatchConfig = "fetchYoutubeTrailerWatchConfig"
    static let loadStreams = "loadStreams"
    static let notifyReleasedEpisodes = "notifyReleasedEpisodes"
    static let prefetchDetailStreams = "prefetchDetailStreams"
    static let prefetchNextEpisodeStreams = "prefetchNextEpisodeStreams"
    static let prepareDirectPlayback = "prepareDirectPlayback"
    static let readCalendarMonth = "readCalendarMonth"
    static let readDetailLocalState = "readDetailLocalState"
    static let readDiscoverCatalogFilters = "readDiscoverCatalogFilters"
    static let readHomeBootstrap = "readHomeBootstrap"
    static let refreshContinueWatching = "refreshContinueWatching"
    static let readLibraryState = "readLibraryState"
    static let readPlaybackProgress = "readPlaybackProgress"
    static let refreshAuthToken = "refreshAuthToken"
    static let refreshInstalledAddons = "refreshInstalledAddons"
    static let replaceExternalContinueWatching = "replaceExternalContinueWatching"
    static let resolveIntroImdbId = "resolveIntroImdbId"
    static let runAuthFlow = "runAuthFlow"
    static let runDiscover = "runDiscover"
    static let runExternalSync = "runExternalSync"
    static let runSearch = "runSearch"
    static let startTorrentStream = "startTorrentStream"
    static let stopTorrent = "stopTorrent"
    static let syncExternalIntegration = "syncExternalIntegration"
    static let syncWatchedState = "syncWatchedState"
    static let updateCalendarWidget = "updateCalendarWidget"
    static let writeFeedback = "writeFeedback"
    static let writeLibraryCommand = "writeLibraryCommand"
    static let writePlaybackProgress = "writePlaybackProgress"
    static let writeSettings = "writeSettings"

    static let all: Set<String> = [
        clearPlaybackProgress,
        enqueueOfflineDownload,
        enqueueTraktScrobble,
        exchangeAuthCode,
        executePlugin,
        fetchAddonManifest,
        fetchAddonResource,
        fetchCatalogPage,
        fetchDiscoverPage,
        fetchDetailSecondary,
        fetchDetailStreams,
        fetchIntroSegments,
        fetchMetaDetail,
        fetchMetaDetailLookup,
        fetchPluginManifest,
        fetchSeasonEpisodes,
        fetchSubtitles,
        fetchYoutubeTrailerPlayer,
        fetchYoutubeTrailerPlayerScript,
        fetchYoutubeTrailerWatchConfig,
        loadStreams,
        notifyReleasedEpisodes,
        prefetchDetailStreams,
        prefetchNextEpisodeStreams,
        prepareDirectPlayback,
        readCalendarMonth,
        readDetailLocalState,
        readDiscoverCatalogFilters,
        readHomeBootstrap,
        refreshContinueWatching,
        readLibraryState,
        readPlaybackProgress,
        refreshAuthToken,
        refreshInstalledAddons,
        replaceExternalContinueWatching,
        resolveIntroImdbId,
        runAuthFlow,
        runDiscover,
        runExternalSync,
        runSearch,
        startTorrentStream,
        stopTorrent,
        syncExternalIntegration,
        syncWatchedState,
        updateCalendarWidget,
        writeFeedback,
        writeLibraryCommand,
        writePlaybackProgress,
        writeSettings,
    ]
}
