// Generated by scripts/generate-headless-contracts.mjs — do not edit.
enum FluxaHeadlessActionType {
    static let navigationRequested = "navigationRequested"
    static let detailLoadRequested = "detailLoadRequested"
    static let detailLocalStateRequested = "detailLocalStateRequested"
    static let detailSecondaryRequested = "detailSecondaryRequested"
    static let detailPrefetchRequested = "detailPrefetchRequested"
    static let detailStreamsRequested = "detailStreamsRequested"
    static let detailStreamsAppended = "detailStreamsAppended"
    static let detailSelectedAddonChanged = "detailSelectedAddonChanged"
    static let metaDetailRequested = "metaDetailRequested"
    static let directPlaybackRequested = "directPlaybackRequested"
    static let introSegmentsRequested = "introSegmentsRequested"
    static let introImdbIdRequested = "introImdbIdRequested"
    static let playerLoadStreamsRequested = "playerLoadStreamsRequested"
    static let playerStreamsLoaded = "playerStreamsLoaded"
    static let playerStreamsFailed = "playerStreamsFailed"
    static let playerResolvePlaybackRequested = "playerResolvePlaybackRequested"
    static let scrobbleRequested = "scrobbleRequested"
    static let profileActivated = "profileActivated"
    static let homeLoadRequested = "homeLoadRequested"
    static let refreshContinueWatchingRequested = "refreshContinueWatchingRequested"
    static let libraryHydrateRequested = "libraryHydrateRequested"
    static let toggleWatchlistRequested = "toggleWatchlistRequested"
    static let toggleLibraryStatusRequested = "toggleLibraryStatusRequested"
    static let setFeedbackRequested = "setFeedbackRequested"
    static let clearPlaybackProgressRequested = "clearPlaybackProgressRequested"
    static let savePlaybackProgressRequested = "savePlaybackProgressRequested"
    static let markWatchedRequested = "markWatchedRequested"
    static let addonInstallRequested = "addonInstallRequested"
    static let addonsRefreshRequested = "addonsRefreshRequested"
    static let addonResourceRequested = "addonResourceRequested"
    static let searchRequested = "searchRequested"
    static let discoverRequested = "discoverRequested"
    static let discoverCatalogFiltersRequested = "discoverCatalogFiltersRequested"
    static let discoverPageRequested = "discoverPageRequested"
    static let catalogPageRequested = "catalogPageRequested"
    static let detailSeasonRequested = "detailSeasonRequested"
    static let playerNextEpisodeCardShown = "playerNextEpisodeCardShown"
    static let subtitleLoadRequested = "subtitleLoadRequested"
    static let externalSyncRequested = "externalSyncRequested"
    static let authFlowRequested = "authFlowRequested"
    static let authExchangeRequested = "authExchangeRequested"
    static let authRefreshRequested = "authRefreshRequested"
    static let externalIntegrationSyncRequested = "externalIntegrationSyncRequested"
    static let settingsChanged = "settingsChanged"
    static let calendarMonthRequested = "calendarMonthRequested"
    static let offlineDownloadRequested = "offlineDownloadRequested"
    static let trailerResolveRequested = "trailerResolveRequested"
    static let trailerPrewarmRequested = "trailerPrewarmRequested"
    static let pluginRepositoryAddRequested = "pluginRepositoryAddRequested"
    static let pluginRepositoryRemoveRequested = "pluginRepositoryRemoveRequested"
    static let pluginScraperToggled = "pluginScraperToggled"
    static let pluginScraperSettingsUpdated = "pluginScraperSettingsUpdated"

    static let all: Set<String> = [
        navigationRequested,
        detailLoadRequested,
        detailLocalStateRequested,
        detailSecondaryRequested,
        detailPrefetchRequested,
        detailStreamsRequested,
        detailStreamsAppended,
        detailSelectedAddonChanged,
        metaDetailRequested,
        directPlaybackRequested,
        introSegmentsRequested,
        introImdbIdRequested,
        playerLoadStreamsRequested,
        playerStreamsLoaded,
        playerStreamsFailed,
        playerResolvePlaybackRequested,
        scrobbleRequested,
        profileActivated,
        homeLoadRequested,
        refreshContinueWatchingRequested,
        libraryHydrateRequested,
        toggleWatchlistRequested,
        toggleLibraryStatusRequested,
        setFeedbackRequested,
        clearPlaybackProgressRequested,
        savePlaybackProgressRequested,
        markWatchedRequested,
        addonInstallRequested,
        addonsRefreshRequested,
        addonResourceRequested,
        searchRequested,
        discoverRequested,
        discoverCatalogFiltersRequested,
        discoverPageRequested,
        catalogPageRequested,
        detailSeasonRequested,
        playerNextEpisodeCardShown,
        subtitleLoadRequested,
        externalSyncRequested,
        authFlowRequested,
        authExchangeRequested,
        authRefreshRequested,
        externalIntegrationSyncRequested,
        settingsChanged,
        calendarMonthRequested,
        offlineDownloadRequested,
        trailerResolveRequested,
        trailerPrewarmRequested,
        pluginRepositoryAddRequested,
        pluginRepositoryRemoveRequested,
        pluginScraperToggled,
        pluginScraperSettingsUpdated,
    ]
}
