// Generated by scripts/generate-headless-contracts.mjs — do not edit.
package com.fluxa.app.core.rust

object FluxaHeadlessEffectType {
    const val ClearPlaybackProgress = "clearPlaybackProgress"
    const val EnqueueOfflineDownload = "enqueueOfflineDownload"
    const val EnqueueTraktScrobble = "enqueueTraktScrobble"
    const val ExchangeAuthCode = "exchangeAuthCode"
    const val ExecutePlugin = "executePlugin"
    const val FetchAddonManifest = "fetchAddonManifest"
    const val FetchAddonResource = "fetchAddonResource"
    const val FetchCatalogPage = "fetchCatalogPage"
    const val FetchDiscoverPage = "fetchDiscoverPage"
    const val FetchDetailSecondary = "fetchDetailSecondary"
    const val FetchDetailStreams = "fetchDetailStreams"
    const val FetchIntroSegments = "fetchIntroSegments"
    const val FetchMetaDetail = "fetchMetaDetail"
    const val FetchMetaDetailLookup = "fetchMetaDetailLookup"
    const val FetchPluginManifest = "fetchPluginManifest"
    const val FetchSeasonEpisodes = "fetchSeasonEpisodes"
    const val FetchSubtitles = "fetchSubtitles"
    const val FetchYoutubeTrailerPlayer = "fetchYoutubeTrailerPlayer"
    const val FetchYoutubeTrailerPlayerScript = "fetchYoutubeTrailerPlayerScript"
    const val FetchYoutubeTrailerWatchConfig = "fetchYoutubeTrailerWatchConfig"
    const val LoadStreams = "loadStreams"
    const val NotifyReleasedEpisodes = "notifyReleasedEpisodes"
    const val PrefetchDetailStreams = "prefetchDetailStreams"
    const val PrefetchNextEpisodeStreams = "prefetchNextEpisodeStreams"
    const val PrepareDirectPlayback = "prepareDirectPlayback"
    const val ReadCalendarMonth = "readCalendarMonth"
    const val ReadDetailLocalState = "readDetailLocalState"
    const val ReadDiscoverCatalogFilters = "readDiscoverCatalogFilters"
    const val ReadHomeBootstrap = "readHomeBootstrap"
    const val RefreshContinueWatching = "refreshContinueWatching"
    const val ReadLibraryState = "readLibraryState"
    const val ReadPlaybackProgress = "readPlaybackProgress"
    const val RefreshAuthToken = "refreshAuthToken"
    const val RefreshInstalledAddons = "refreshInstalledAddons"
    const val ReplaceExternalContinueWatching = "replaceExternalContinueWatching"
    const val ResolveIntroImdbId = "resolveIntroImdbId"
    const val RunAuthFlow = "runAuthFlow"
    const val RunDiscover = "runDiscover"
    const val RunExternalSync = "runExternalSync"
    const val RunSearch = "runSearch"
    const val StartTorrentStream = "startTorrentStream"
    const val StopTorrent = "stopTorrent"
    const val SyncExternalIntegration = "syncExternalIntegration"
    const val SyncWatchedState = "syncWatchedState"
    const val UpdateCalendarWidget = "updateCalendarWidget"
    const val WriteFeedback = "writeFeedback"
    const val WriteLibraryCommand = "writeLibraryCommand"
    const val WritePlaybackProgress = "writePlaybackProgress"
    const val WriteSettings = "writeSettings"

    val all: Set<String> = setOf(
        ClearPlaybackProgress,
        EnqueueOfflineDownload,
        EnqueueTraktScrobble,
        ExchangeAuthCode,
        ExecutePlugin,
        FetchAddonManifest,
        FetchAddonResource,
        FetchCatalogPage,
        FetchDiscoverPage,
        FetchDetailSecondary,
        FetchDetailStreams,
        FetchIntroSegments,
        FetchMetaDetail,
        FetchMetaDetailLookup,
        FetchPluginManifest,
        FetchSeasonEpisodes,
        FetchSubtitles,
        FetchYoutubeTrailerPlayer,
        FetchYoutubeTrailerPlayerScript,
        FetchYoutubeTrailerWatchConfig,
        LoadStreams,
        NotifyReleasedEpisodes,
        PrefetchDetailStreams,
        PrefetchNextEpisodeStreams,
        PrepareDirectPlayback,
        ReadCalendarMonth,
        ReadDetailLocalState,
        ReadDiscoverCatalogFilters,
        ReadHomeBootstrap,
        RefreshContinueWatching,
        ReadLibraryState,
        ReadPlaybackProgress,
        RefreshAuthToken,
        RefreshInstalledAddons,
        ReplaceExternalContinueWatching,
        ResolveIntroImdbId,
        RunAuthFlow,
        RunDiscover,
        RunExternalSync,
        RunSearch,
        StartTorrentStream,
        StopTorrent,
        SyncExternalIntegration,
        SyncWatchedState,
        UpdateCalendarWidget,
        WriteFeedback,
        WriteLibraryCommand,
        WritePlaybackProgress,
        WriteSettings,
    )
}
