// Generated by scripts/generate-headless-contracts.mjs — do not edit.
package com.fluxa.app.core.rust

object FluxaHeadlessActionType {
    const val NavigationRequested = "navigationRequested"
    const val DetailLoadRequested = "detailLoadRequested"
    const val DetailLocalStateRequested = "detailLocalStateRequested"
    const val DetailSecondaryRequested = "detailSecondaryRequested"
    const val DetailPrefetchRequested = "detailPrefetchRequested"
    const val DetailStreamsRequested = "detailStreamsRequested"
    const val DetailStreamsAppended = "detailStreamsAppended"
    const val DetailSelectedAddonChanged = "detailSelectedAddonChanged"
    const val MetaDetailRequested = "metaDetailRequested"
    const val DirectPlaybackRequested = "directPlaybackRequested"
    const val IntroSegmentsRequested = "introSegmentsRequested"
    const val IntroImdbIdRequested = "introImdbIdRequested"
    const val PlayerLoadStreamsRequested = "playerLoadStreamsRequested"
    const val PlayerStreamsLoaded = "playerStreamsLoaded"
    const val PlayerStreamsFailed = "playerStreamsFailed"
    const val PlayerResolvePlaybackRequested = "playerResolvePlaybackRequested"
    const val ScrobbleRequested = "scrobbleRequested"
    const val ProfileActivated = "profileActivated"
    const val HomeLoadRequested = "homeLoadRequested"
    const val RefreshContinueWatchingRequested = "refreshContinueWatchingRequested"
    const val LibraryHydrateRequested = "libraryHydrateRequested"
    const val ToggleWatchlistRequested = "toggleWatchlistRequested"
    const val ToggleLibraryStatusRequested = "toggleLibraryStatusRequested"
    const val SetFeedbackRequested = "setFeedbackRequested"
    const val ClearPlaybackProgressRequested = "clearPlaybackProgressRequested"
    const val SavePlaybackProgressRequested = "savePlaybackProgressRequested"
    const val MarkWatchedRequested = "markWatchedRequested"
    const val AddonInstallRequested = "addonInstallRequested"
    const val AddonsRefreshRequested = "addonsRefreshRequested"
    const val AddonResourceRequested = "addonResourceRequested"
    const val SearchRequested = "searchRequested"
    const val DiscoverRequested = "discoverRequested"
    const val DiscoverCatalogFiltersRequested = "discoverCatalogFiltersRequested"
    const val DiscoverPageRequested = "discoverPageRequested"
    const val CatalogPageRequested = "catalogPageRequested"
    const val DetailSeasonRequested = "detailSeasonRequested"
    const val PlayerNextEpisodeCardShown = "playerNextEpisodeCardShown"
    const val SubtitleLoadRequested = "subtitleLoadRequested"
    const val ExternalSyncRequested = "externalSyncRequested"
    const val AuthFlowRequested = "authFlowRequested"
    const val AuthExchangeRequested = "authExchangeRequested"
    const val AuthRefreshRequested = "authRefreshRequested"
    const val ExternalIntegrationSyncRequested = "externalIntegrationSyncRequested"
    const val SettingsChanged = "settingsChanged"
    const val CalendarMonthRequested = "calendarMonthRequested"
    const val OfflineDownloadRequested = "offlineDownloadRequested"
    const val TrailerResolveRequested = "trailerResolveRequested"
    const val TrailerPrewarmRequested = "trailerPrewarmRequested"
    const val PluginRepositoryAddRequested = "pluginRepositoryAddRequested"
    const val PluginRepositoryRemoveRequested = "pluginRepositoryRemoveRequested"
    const val PluginScraperToggled = "pluginScraperToggled"
    const val PluginScraperSettingsUpdated = "pluginScraperSettingsUpdated"

    val all: Set<String> = setOf(
        NavigationRequested,
        DetailLoadRequested,
        DetailLocalStateRequested,
        DetailSecondaryRequested,
        DetailPrefetchRequested,
        DetailStreamsRequested,
        DetailStreamsAppended,
        DetailSelectedAddonChanged,
        MetaDetailRequested,
        DirectPlaybackRequested,
        IntroSegmentsRequested,
        IntroImdbIdRequested,
        PlayerLoadStreamsRequested,
        PlayerStreamsLoaded,
        PlayerStreamsFailed,
        PlayerResolvePlaybackRequested,
        ScrobbleRequested,
        ProfileActivated,
        HomeLoadRequested,
        RefreshContinueWatchingRequested,
        LibraryHydrateRequested,
        ToggleWatchlistRequested,
        ToggleLibraryStatusRequested,
        SetFeedbackRequested,
        ClearPlaybackProgressRequested,
        SavePlaybackProgressRequested,
        MarkWatchedRequested,
        AddonInstallRequested,
        AddonsRefreshRequested,
        AddonResourceRequested,
        SearchRequested,
        DiscoverRequested,
        DiscoverCatalogFiltersRequested,
        DiscoverPageRequested,
        CatalogPageRequested,
        DetailSeasonRequested,
        PlayerNextEpisodeCardShown,
        SubtitleLoadRequested,
        ExternalSyncRequested,
        AuthFlowRequested,
        AuthExchangeRequested,
        AuthRefreshRequested,
        ExternalIntegrationSyncRequested,
        SettingsChanged,
        CalendarMonthRequested,
        OfflineDownloadRequested,
        TrailerResolveRequested,
        TrailerPrewarmRequested,
        PluginRepositoryAddRequested,
        PluginRepositoryRemoveRequested,
        PluginScraperToggled,
        PluginScraperSettingsUpdated,
    )
}
