use super::*;

type Router = fn(&str, &str) -> Outcome;

pub(super) fn router_for(method: &str) -> Option<Router> {
    METHODS
        .binary_search_by(|(name, _)| name.cmp(&method))
        .ok()
        .map(|index| METHODS[index].1)
}

static METHODS: &[(&str, Router)] = &[
    ("accountSource", route_profile_contract),
    ("activeProfilePlan", route_profile_contract),
    ("addonCollectionMutationPlan", route_resource_plan),
    ("addonProfileMutationPlan", route_addon_store),
    ("addonResourceRequestPlan", route_resource_plan),
    ("addonStoreEntriesPlan", route_addon_store),
    ("addonStoreInputType", route_addon_store),
    ("addonStoreSearchPolicy", route_addon_store),
    ("addonStreamsWithProvider", route_resource_plan),
    ("addonUptimeMatchPlan", route_addon_uptime),
    ("airDateRefreshCandidates", route_watchlist),
    ("airDateRefreshPlan", route_watchlist),
    ("anilistCalendarPlan", route_provider_library),
    ("anilistEntriesToSync", route_external_sync_anilist),
    ("anilistGraphqlQueries", route_external_sync_anilist),
    ("anilistId", route_intro_segments),
    ("anilistMalId", route_intro_segments),
    ("anilistMediaIdPlan", route_intro_segments),
    ("anilistMediaListStatus", route_external_sync_anilist),
    (
        "anilistSaveMediaListEntryVariables",
        route_external_sync_anilist,
    ),
    ("anilistSearchBestMatch", route_external_sync_anilist),
    ("anime4kShaderChain", route_player_policy),
    ("animeSkipFindEpisodesPlan", route_intro_segments),
    ("animeSkipFindShowPlan", route_intro_segments),
    ("animeSkipFindTimestampsPlan", route_intro_segments),
    ("animeSkipShowId", route_intro_segments),
    ("aniskipSegmentsPlan", route_intro_segments),
    ("annotateCatalogItems", route_library_state),
    ("app.create", route_engine_lifecycle),
    ("app.destroy", route_engine_lifecycle),
    ("app.dispatch", route_engine_lifecycle),
    ("app.dispatchDelta", route_engine_lifecycle),
    ("app.state", route_engine_lifecycle),
    ("applyAirDateUpdates", route_watchlist),
    ("applyPreferenceUpdate", route_resource_plan),
    ("audioPcmChannelCount", route_player_policy),
    ("baseUrl", route_addon_protocol),
    ("buildBillboardPool", route_library_state),
    ("buildContentWarnings", route_content_warnings),
    ("buildContinueWatchingFromProgress", route_library_state),
    ("buildHomeCollectionShelves", route_library_state),
    ("buildMetadataFeedOptions", route_search_plan),
    ("buildResourceUrl", route_addon_protocol),
    ("buildTraktIds", route_content_identity),
    ("cacheEntryPolicy", route_data_policy),
    ("cacheTrimPolicy", route_data_policy),
    ("calendarCandidatePlan", route_calendar),
    ("calendarContentPlan", route_calendar),
    ("calendarItemMatchesMonth", route_calendar),
    ("calendarItemsFromMeta", route_calendar),
    ("calendarNotificationContent", route_calendar),
    ("calendarReleaseDetection", route_calendar),
    ("calendarReleaseRows", route_calendar),
    ("calendarSeasonCandidates", route_calendar),
    ("calendarVisibilityPlan", route_calendar),
    ("calendarWidgetRows", route_calendar),
    ("canPrefetchNextEpisode", route_player_policy),
    ("catalogHasRequiredExtraExcept", route_addon_protocol),
    ("catalogRequiresExtra", route_addon_protocol),
    ("catalogSearchEligible", route_addon_protocol),
    ("catalogSupportsExtra", route_addon_protocol),
    ("chapterSkipSegments", route_player_policy),
    ("classifyMetaLinks", route_addon_protocol),
    ("clearPlaybackProgressItem", route_library_state),
    ("clearPlaybackProgressPlan", route_library_state),
    ("cloudstreamContentType", route_stream_policy),
    ("cloudstreamMatchScore", route_stream_policy),
    ("cloudstreamQualityLabel", route_stream_policy),
    ("cloudstreamQualityScore", route_stream_policy),
    ("cloudstreamStreamOrder", route_stream_policy),
    ("collectionFolderItemsPlan", route_watchlist),
    ("collectionFolderPresentation", route_watchlist),
    ("collectionFolderTabsPlan", route_watchlist),
    ("collectionMergePlan", route_watchlist),
    ("collectionMutationPlan", route_watchlist),
    ("computeContinueWatchingBadges", route_library_state),
    ("connectedProviders", route_provider_library),
    ("contentBaseId", route_content_identity),
    ("contentImdbId", route_content_identity),
    ("contentMatchesFilter", route_content_identity),
    ("contentMergeKeys", route_content_identity),
    ("contentTraktKeysBatch", route_content_identity),
    ("contentWarningUrl", route_content_warnings),
    ("contentWatchedKeysBatch", route_content_identity),
    ("continueWatchingCardFields", route_library_state),
    ("continueWatchingForSource", route_library_state),
    ("continueWatchingProgressFields", route_library_state),
    ("continueWatchingResumePlan", route_library_state),
    ("continueWatchingSourcePlan", route_library_state),
    ("core.drainErrorLog", route_engine_lifecycle),
    ("coreCapabilities", route_core_contract),
    ("coreContractManifest", route_core_contract),
    ("createProfilePlan", route_profile_contract),
    ("cs3CatalogFeedKey", route_content_identity),
    ("cs3MetadataFeedOptions", route_content_identity),
    ("cs3PluginFeedKey", route_content_identity),
    ("curateHomeItems", route_library_state),
    ("dataFailurePolicy", route_data_policy),
    ("desktopCalendarReadPlan", route_calendar),
    ("detailAvailableSeasons", route_search_plan),
    ("detailEpisodePlan", route_resource_plan),
    ("detailLoadPlan", route_search_plan),
    ("detailSeasonLoadPlan", route_search_plan),
    ("detailSeasonVideos", route_search_plan),
    ("detailSeriesLookupId", route_search_plan),
    ("detailStreamResultPlan", route_headless_adapter_plan),
    ("detectAnimePlayback", route_anime_detection),
    ("deviceAuthStart", route_device_auth),
    ("deviceAuthTransition", route_device_auth),
    ("deviceResourceBudget", route_device_resource),
    ("directPlaybackPlan", route_content_identity),
    ("directPlaybackPolicy", route_headless_adapter_plan),
    ("discordPresenceSnapshot", route_discord_presence),
    ("discoverCatalogCacheKey", route_content_identity),
    ("discoverCatalogCandidates", route_search_plan),
    ("discoverCatalogOptions", route_search_plan),
    ("discoverCatalogRequestTypes", route_search_plan),
    ("discoverContentTypes", route_search_plan),
    ("discoverSelectionPlan", route_search_plan),
    ("discoverSortPlan", route_search_plan),
    ("discoverSourceRequests", route_search_plan),
    ("dvProxyPlan", route_player_policy),
    ("effectiveAddonsOwnerId", route_addon_store),
    ("effectiveMetadataFeedSelection", route_content_identity),
    ("effectivePluginsOwnerId", route_addon_store),
    ("engine.completeEffect", route_engine_lifecycle),
    ("engine.create", route_engine_lifecycle),
    ("engine.destroy", route_engine_lifecycle),
    ("engine.dispatch", route_engine_lifecycle),
    ("engine.snapshot", route_engine_lifecycle),
    ("episodeFilenameCandidate", route_content_identity),
    ("episodeTextMatches", route_content_identity),
    ("exportCollections", route_watchlist),
    ("externalAudioOptions", route_stream_policy),
    ("externalProviderActionPlan", route_external_sync_trakt),
    ("externalSyncRefreshRetryAction", route_external_sync_trakt),
    ("externalSyncResponseAction", route_external_sync_trakt),
    ("externalSyncWorkerRetryAction", route_external_sync_trakt),
    ("extractAddonManifestUrl", route_addon_store),
    ("extractAnilistIdFromLinks", route_external_sync_anilist),
    ("filterDiscoverResults", route_content_identity),
    ("filterEnabledAddons", route_addon_store),
    ("filterHomeCategories", route_library_state),
    ("filterHomeContinueWatching", route_library_state),
    ("findPreferredSubtitleIndex", route_stream_policy),
    ("fluxaSyncApplyPull", route_fluxa_sync),
    ("fluxaSyncApplyPushResult", route_fluxa_sync),
    ("fluxaSyncDocuments", route_fluxa_sync),
    ("fluxaSyncProfilePlan", route_fluxa_sync),
    ("fluxaSyncPushPlan", route_fluxa_sync),
    ("folderPageState", route_library_state),
    ("folderSourcePagePlan", route_library_state),
    ("formatEpisodeLine", route_library_state),
    ("formatRuntimeLabel", route_library_state),
    ("homeBillboardCandidateScore", route_library_state),
    ("homeBillboardEditorialMatchScore", route_library_state),
    ("homeBillboardHasBackdrop", route_library_state),
    ("homeBillboardIdentityKey", route_library_state),
    ("homeBillboardNormalizedTitle", route_library_state),
    ("homeBillboardVisualScore", route_library_state),
    ("homeHeroEpisodePlan", route_library_state),
    ("homeHeroPlan", route_library_state),
    ("homeMetadataFeedPlan", route_library_state),
    ("homeOverlapRatio", route_library_state),
    ("homePersonalizationScore", route_library_state),
    ("identity", route_addon_protocol),
    ("importApplyPlan", route_external_sync_trakt),
    ("importCollections", route_watchlist),
    ("integrationSettingsPlan", route_resource_plan),
    ("introDbSegmentsPlan", route_intro_segments),
    ("introDbSubmitPlan", route_intro_segments),
    ("isEpisodeReleased", route_library_state),
    ("isSecureRemoteUrl", route_addon_store),
    ("isSeriesContentType", route_content_identity),
    ("isTmdbLikeContentId", route_content_identity),
    ("isUpNextContinueWatchingItem", route_library_state),
    ("itemListDiff", route_library_state),
    ("itemListNewEntries", route_library_state),
    ("libraryApplyMarkWatched", route_watchlist),
    ("libraryCollectionImportValidation", route_watchlist),
    ("libraryCommandPlan", route_watchlist),
    ("libraryContinueWatchingItems", route_library_state),
    ("libraryDocumentViews", route_library_state),
    ("libraryExternalMergePlan", route_watchlist),
    ("libraryLocalStatePlan", route_resource_plan),
    ("libraryOfflineGrouping", route_watchlist),
    ("librarySortPlan", route_search_plan),
    ("libraryViewPlan", route_watchlist),
    ("libraryWatchlistItems", route_library_state),
    ("localMediaAcceptsContentType", route_local_media),
    ("localMediaContentType", route_local_media),
    ("localMediaIsVideoFile", route_local_media),
    ("localMediaNormalizedTitle", route_local_media),
    ("localMediaParseFilename", route_local_media),
    ("localMediaRequestedContentType", route_local_media),
    ("localMediaResolveVideo", route_local_media),
    ("localMediaScoreCandidate", route_local_media),
    ("localMediaTitleSimilarity", route_local_media),
    ("manifestCandidates", route_addon_protocol),
    ("manifestFetchDecision", route_resource_plan),
    ("manifestFetchPlan", route_addon_protocol),
    ("markSeasonsActionPlan", route_resource_plan),
    ("matchAnimeSkipEpisodeId", route_intro_segments),
    ("matchStreamBadges", route_stream_badges),
    ("mdblistBearer", route_mdblist),
    ("mdblistCalendarPlan", route_provider_library),
    ("mdblistCatalogUrl", route_mdblist),
    ("mdblistCheckinPlan", route_mdblist),
    ("mdblistContentType", route_mdblist),
    ("mdblistDevicePollOutcome", route_mdblist),
    ("mdblistDiscussionCommentDeletePlan", route_mdblist),
    ("mdblistDiscussionCommentLikePlan", route_mdblist),
    ("mdblistDiscussionCommentUpdatePlan", route_mdblist),
    ("mdblistDiscussionCreatePlan", route_mdblist),
    ("mdblistDiscussionHotUrl", route_mdblist),
    ("mdblistDiscussionRepliesUrl", route_mdblist),
    ("mdblistDiscussionReplyCreatePlan", route_mdblist),
    ("mdblistDiscussionReplyDeletePlan", route_mdblist),
    ("mdblistDiscussionReplyLikePlan", route_mdblist),
    ("mdblistDiscussionReplyUpdatePlan", route_mdblist),
    ("mdblistDiscussionSummaryUrl", route_mdblist),
    ("mdblistDiscussionUrl", route_mdblist),
    ("mdblistGenresUrl", route_mdblist),
    ("mdblistListByNameUrl", route_mdblist),
    ("mdblistListChangesUrl", route_mdblist),
    ("mdblistListCreatePlan", route_mdblist),
    ("mdblistListDeletePlan", route_mdblist),
    ("mdblistListInfoUrl", route_mdblist),
    ("mdblistListItemsMutatePlan", route_mdblist),
    ("mdblistListItemsResponseToMetas", route_mdblist),
    ("mdblistListItemsUrl", route_mdblist),
    ("mdblistListLikePlan", route_mdblist),
    ("mdblistListMembershipUrl", route_mdblist),
    ("mdblistListUpdatePlan", route_mdblist),
    ("mdblistListsCuratedUrl", route_mdblist),
    ("mdblistListsLikedUrl", route_mdblist),
    ("mdblistListsOfficialUrl", route_mdblist),
    ("mdblistListsRecommendedUrl", route_mdblist),
    ("mdblistListsSearchUrl", route_mdblist),
    ("mdblistListsTopUrl", route_mdblist),
    ("mdblistListsUserUrl", route_mdblist),
    ("mdblistMediaInfoBatchPlan", route_mdblist),
    ("mdblistMediaInfoUrl", route_mdblist),
    ("mdblistMediaRatingsFromResponse", route_mdblist),
    ("mdblistPublicUserUrl", route_mdblist),
    ("mdblistRatingsBatchPlan", route_mdblist),
    ("mdblistScrobblePlan", route_mdblist),
    ("mdblistSearchUrl", route_mdblist),
    ("mdblistSyncGetUrl", route_mdblist),
    ("mdblistSyncMutatePlan", route_mdblist),
    ("mdblistUpnextUrl", route_mdblist),
    ("mdblistUserFollowPlan", route_mdblist),
    ("mdblistUserStatsUrl", route_mdblist),
    ("mdblistUserUrl", route_mdblist),
    ("mdblistWatchlistItemsUrl", route_mdblist),
    ("mdblistWatchlistMutatePlan", route_mdblist),
    ("mdblistWatchproviderLinksUrl", route_mdblist),
    ("mergeContinueWatchingLists", route_external_sync_trakt),
    ("mergeDiscoverPages", route_search_plan),
    ("mergeDiscoverSources", route_search_plan),
    ("mergeExternalWatched", route_external_sync_trakt),
    ("mergeExternalWatchlist", route_external_sync_trakt),
    ("mergeFolderSources", route_library_state),
    ("mergeIntroSegments", route_intro_segments),
    ("mergeLibraryItemsById", route_external_sync_anilist),
    ("mergeLiveManifest", route_addon_protocol),
    ("mergeProgressMeta", route_watchlist),
    ("mergeSearchSources", route_search_plan),
    ("mergeWatchedTimestamped", route_external_sync_trakt),
    ("mergeWatchlistTimestamped", route_external_sync_trakt),
    ("moveMetadataFeedOrder", route_content_identity),
    ("nextProgressInfoPlan", route_library_state),
    ("nextRetrySourcePlan", route_player_policy),
    ("nextUnairedEpisode", route_calendar),
    ("normalizeAddonDescriptor", route_addon_protocol),
    ("normalizeAddonSubtitles", route_addon_resource),
    ("normalizeCatalogType", route_content_identity),
    ("normalizeCloudstreamRepoInput", route_addon_store),
    ("normalizeCloudstreamRepoUrl", route_addon_store),
    ("normalizeContentType", route_content_identity),
    ("normalizeHomeCatalogItems", route_library_state),
    ("normalizeLibraryDocument", route_library_state),
    ("normalizeManifestUrl", route_addon_protocol),
    ("normalizePluginRepositoryUrl", route_addon_store),
    ("normalizeSeriesLookupId", route_content_identity),
    ("normalizeStreamBadgeRules", route_stream_badges),
    ("normalizeTrailerSubtitleUrl", route_trailer_subtitles),
    ("nuvioAddonReconciliationPlan", route_nuvio_sync),
    ("nuvioAddonSnapshotPlan", route_nuvio_sync),
    ("nuvioAddonState", route_nuvio_sync),
    ("nuvioApplyDeltaSync", route_nuvio_sync),
    ("nuvioApplyProgressSync", route_nuvio_sync),
    ("nuvioApplyRemoteProfiles", route_nuvio_sync),
    ("nuvioBuildLocalProfiles", route_nuvio_sync),
    ("nuvioCandidateContentTypes", route_nuvio_sync),
    ("nuvioCanonicalContentType", route_nuvio_sync),
    ("nuvioCollectionRequest", route_nuvio_sync),
    ("nuvioDeltaSyncRequestPlan", route_nuvio_sync),
    ("nuvioEffectiveProfileScopes", route_nuvio_sync),
    ("nuvioExportPushPlan", route_nuvio_sync),
    ("nuvioHomeLayout", route_nuvio_sync),
    ("nuvioImportMergePlan", route_nuvio_sync),
    ("nuvioLibraryItemRequest", route_nuvio_sync),
    ("nuvioLibraryMutationPlan", route_nuvio_sync),
    ("nuvioLibraryToWatchlist", route_nuvio_sync),
    ("nuvioMapCollections", route_nuvio_sync),
    ("nuvioPinCachePayload", route_nuvio_pin),
    ("nuvioPinHash", route_nuvio_pin),
    ("nuvioPinVerifyCached", route_nuvio_pin),
    ("nuvioPlaybackProgressRequest", route_nuvio_sync),
    ("nuvioPluginContentId", route_nuvio_sync),
    ("nuvioPluginContentType", route_nuvio_sync),
    ("nuvioProgressMetaNeeds", route_nuvio_sync),
    ("nuvioProgressPresentation", route_nuvio_sync),
    ("nuvioProgressSyncRequestPlan", route_nuvio_sync),
    ("nuvioProviderLibrarySnapshot", route_nuvio_sync),
    ("nuvioResolveContinueWatching", route_nuvio_sync),
    ("nuvioSortAddonsByPriority", route_nuvio_sync),
    ("nuvioWatchedItemsRequest", route_nuvio_sync),
    ("nuvioWriteRequests", route_nuvio_sync),
    ("offlineDownloadPlan", route_offline),
    ("optimizeHomeRows", route_library_state),
    ("orderStreamsPlan", route_player_policy),
    ("orderedMetadataFeedKeys", route_content_identity),
    ("parseAddonResourceResult", route_addon_resource),
    ("parseAddonStreamResult", route_addon_resource),
    ("parseAndPlanAddonResource", route_resource_plan),
    ("parseAnimeSkipResults", route_intro_segments),
    ("parseAniskipResults", route_intro_segments),
    ("parseCatalogItems", route_addon_resource),
    ("parseDirectStreams", route_addon_resource),
    ("parseEpisodeLocator", route_content_identity),
    ("parseExtraArgs", route_content_identity),
    ("parseIntroDbSegments", route_intro_segments),
    ("parseManifest", route_addon_protocol),
    ("parsePublicmetadbSegments", route_intro_segments),
    ("parseSkipdbSegments", route_intro_segments),
    ("parseStreamBadgeImport", route_stream_badges),
    ("parseTheIntroDbSegments", route_intro_segments),
    ("parseTrailerSubtitleCues", route_trailer_subtitles),
    ("parseVideoId", route_content_identity),
    ("partitionThisWeek", route_calendar),
    ("playbackClosePlan", route_player_policy),
    ("playbackIntroLookupContentId", route_content_identity),
    ("playbackPreferencesPlan", route_player_policy),
    ("playbackPreparePlan", route_resource_plan),
    ("playbackProgressItem", route_library_state),
    ("playbackProgressMergePlan", route_watchlist),
    ("playbackProgressWritePlan", route_watchlist),
    ("playbackStreamRequestIds", route_content_identity),
    ("playerBackendSelection", route_player_policy),
    ("playerBufferTargets", route_player_policy),
    ("playerFlowDispatch", route_player_flow),
    ("playerProgressPercent", route_player_scrobble),
    ("playerRetryPolicy", route_player_policy),
    ("playerScrobbleLifecycleAction", route_player_scrobble),
    ("playerShouldEnqueueDurableScrobble", route_player_scrobble),
    ("playerShouldMarkScrobbleStopped", route_player_scrobble),
    ("playerShouldQueueScrobblePause", route_player_scrobble),
    ("playerShouldSaveEventProgress", route_player_scrobble),
    ("playerShouldSaveOnDispose", route_player_scrobble),
    ("playerShouldSavePeriodicProgress", route_player_scrobble),
    ("playerShouldSendScrobbleStart", route_player_scrobble),
    ("playerSourceSidebarPlan", route_player_policy),
    ("playerTrackState", route_stream_policy),
    ("pluginExecutionPlan", route_plugins),
    ("pluginManifestParse", route_plugins),
    ("pluginNetworkAddressAllowed", route_plugins),
    ("pluginNetworkAddressBytesAllowed", route_plugins),
    ("pluginStorageFallback", route_addon_store),
    ("pluginStreamResultsParse", route_plugins),
    ("pluginStreamResultsToStreams", route_plugins),
    ("pluginUpdatePlan", route_plugins),
    ("pluginUrlAllowed", route_plugins),
    ("preferHttpsAssetUrl", route_addon_protocol),
    ("preferencesSchema", route_resource_plan),
    ("prefetchDetailStreamsPlan", route_headless_adapter_plan),
    ("primaryProfileId", route_profile_contract),
    ("prioritizeHomeRows", route_library_state),
    ("profileAvatarDefault", route_profile_contract),
    ("profileAvatarPackCatalog", route_profile_avatar_pack),
    ("profileAvatarPackDiscoveryPlan", route_profile_avatar_pack),
    ("profileAvatarPackManifestPlan", route_profile_avatar_pack),
    ("profileAvatarPackParse", route_profile_avatar_pack),
    ("profileAvatarPackRepositoryPlan", route_profile_avatar_pack),
    ("profileConnectionState", route_profile_contract),
    ("profileDefaultSeed", route_profile_contract),
    ("profileLocalAddonsKey", route_addon_store),
    ("profileMutationPlan", route_profile_contract),
    ("profilePinHash", route_profile_contract),
    ("profilePinMatches", route_profile_contract),
    ("profileSafePrefs", route_profile_prefs),
    ("profileSettingsMigrationPlan", route_profile_contract),
    ("profileSyncMergePlan", route_profile_contract),
    ("promoteExternalProgressPlan", route_external_sync_trakt),
    ("providerAuthCallback", route_provider_library),
    ("providerAuthOutcome", route_provider_library),
    ("providerAuthRequest", route_provider_library),
    ("providerAuthorizeUrl", route_provider_library),
    ("providerAvailabilityPlan", route_headless_adapter_plan),
    ("providerCalendarItems", route_external_sync_trakt),
    ("providerLibraryRequests", route_provider_library),
    ("providerLibrarySnapshot", route_provider_library),
    ("providerPaginationPlan", route_external_sync_trakt),
    ("providerRegistry", route_provider_library),
    ("providerScrobbleRequest", route_provider_library),
    ("providerSearchTerms", route_content_identity),
    ("providerWriteRequests", route_provider_library),
    (
        "publicmetadbAnimeSeasonsDeleteChunkPlan",
        route_publicmetadb,
    ),
    (
        "publicmetadbAnimeSeasonsDeleteMappingPlan",
        route_publicmetadb,
    ),
    ("publicmetadbAnimeSeasonsSubmitPlan", route_publicmetadb),
    ("publicmetadbAnimeSeasonsUrl", route_publicmetadb),
    ("publicmetadbBearer", route_publicmetadb),
    ("publicmetadbCatalogItemsUrl", route_publicmetadb),
    ("publicmetadbCatalogsUrl", route_publicmetadb),
    (
        "publicmetadbEpisodeRatingsBatchCreatePlan",
        route_publicmetadb,
    ),
    (
        "publicmetadbEpisodeRatingsBatchDeletePlan",
        route_publicmetadb,
    ),
    ("publicmetadbEpisodeRatingsBatchUrl", route_publicmetadb),
    ("publicmetadbEpisodeRatingsCreatePlan", route_publicmetadb),
    ("publicmetadbEpisodeRatingsDeletePlan", route_publicmetadb),
    ("publicmetadbEpisodeRatingsUrl", route_publicmetadb),
    ("publicmetadbHighlightsCreatePlan", route_publicmetadb),
    ("publicmetadbHighlightsDeletePlan", route_publicmetadb),
    ("publicmetadbHighlightsUrl", route_publicmetadb),
    ("publicmetadbListItemsAddPlan", route_publicmetadb),
    ("publicmetadbListItemsRemovePlan", route_publicmetadb),
    ("publicmetadbListItemsUrl", route_publicmetadb),
    ("publicmetadbListsCreatePlan", route_publicmetadb),
    ("publicmetadbListsDeletePlan", route_publicmetadb),
    ("publicmetadbListsUrl", route_publicmetadb),
    ("publicmetadbMappingsCreatePlan", route_publicmetadb),
    ("publicmetadbMappingsDeletePlan", route_publicmetadb),
    ("publicmetadbMappingsLookupUrl", route_publicmetadb),
    ("publicmetadbMappingsUrl", route_publicmetadb),
    ("publicmetadbRatingsCreatePlan", route_publicmetadb),
    ("publicmetadbRatingsDeletePlan", route_publicmetadb),
    ("publicmetadbRatingsUrl", route_publicmetadb),
    ("publicmetadbResumeBatchPlan", route_publicmetadb),
    ("publicmetadbResumeDeletePlan", route_publicmetadb),
    ("publicmetadbResumeSavePlan", route_publicmetadb),
    ("publicmetadbResumeUrl", route_publicmetadb),
    ("publicmetadbSkipsCreatePlan", route_publicmetadb),
    ("publicmetadbSkipsDeletePlan", route_publicmetadb),
    ("publicmetadbSkipsUrl", route_publicmetadb),
    ("publicmetadbVotesCreatePlan", route_publicmetadb),
    ("publicmetadbVotesDeletePlan", route_publicmetadb),
    ("publicmetadbVotesUrl", route_publicmetadb),
    ("publicmetadbWatchedBulkDeletePlan", route_publicmetadb),
    ("publicmetadbWatchedDeletePlan", route_publicmetadb),
    ("publicmetadbWatchedEditDatePlan", route_publicmetadb),
    ("publicmetadbWatchedMarkPlan", route_publicmetadb),
    ("publicmetadbWatchedUrl", route_publicmetadb),
    ("pushPlan", route_external_sync_trakt),
    ("recentSearchesPlan", route_search_plan),
    ("recommendationOutroPlan", route_library_state),
    ("releaseDateIsReleased", route_content_identity),
    ("releaseDateRecentlyReleased", route_content_identity),
    ("releaseDateUpcoming", route_content_identity),
    ("rememberLastWatchedEpisodes", route_library_state),
    ("remoteCollectionRequestPlan", route_watchlist),
    ("remoteCollectionResponsePlan", route_watchlist),
    ("removeStreamBadgeSource", route_stream_badges),
    ("replaceExternalContinueWatching", route_external_sync_trakt),
    ("repositoryMetaDetailPlan", route_resource_plan),
    ("repositorySeasonVideos", route_resource_plan),
    ("resolveFeedOptionGenre", route_search_plan),
    ("resolveManifestAssets", route_addon_protocol),
    ("resolveNextAfterWatched", route_library_state),
    ("resolveNextEpisode", route_library_state),
    ("resolvePreferredAudioLanguage", route_stream_policy),
    ("resolveTransportUrl", route_search_plan),
    ("resourceFetchExecutionPolicy", route_resource_plan),
    ("resourceFetchPlan", route_resource_plan),
    ("resourceKindToResource", route_resource_plan),
    ("resourceParsePlan", route_resource_plan),
    ("safeDolbyVisionFallbackMode", route_profile_prefs),
    ("safePlayerBufferCacheMb", route_profile_prefs),
    ("safeStreamSourceSelectionMode", route_profile_prefs),
    ("samePluginRepositoryUrl", route_addon_store),
    ("sanitizeProfile", route_addon_store),
    ("scrobbleCloseAction", route_player_scrobble),
    ("scrobbleMediaContext", route_player_scrobble),
    ("searchResultGrouping", route_search_plan),
    ("searchScreenPlan", route_search_plan),
    ("searchSuggestionsPlan", route_search_plan),
    ("seasonWatchedPlan", route_resource_plan),
    ("selectAudioTrack", route_player_policy),
    ("selectContinueWatchingArtwork", route_library_state),
    ("selectNextEpisodeStream", route_player_policy),
    ("selectStreamIndex", route_stream_policy),
    ("setActiveStreamBadgeSource", route_stream_badges),
    ("setMetadataFeedGroupEnabled", route_content_identity),
    ("sha256VerificationStatus", route_addon_store),
    ("shortenSynopsis", route_content_identity),
    ("shouldAttemptAnimeTracking", route_anime_detection),
    ("shuffleEpisodePick", route_player_policy),
    ("simklCalendarPlan", route_provider_library),
    ("simklHistoryRequest", route_external_sync_simkl),
    ("simklLibraryToItems", route_external_sync_simkl),
    ("simklLookupIdForType", route_external_sync_simkl),
    ("simklMarkWatchedBody", route_external_sync_simkl),
    ("simklMatchEpisode", route_external_sync_simkl),
    ("simklMergePlaybackProgress", route_external_sync_simkl),
    ("simklPlaybackDeleteIds", route_external_sync_simkl),
    ("simklPlaybackItemToContinueMeta", route_external_sync_simkl),
    ("simklRecommendationCandidates", route_external_sync_simkl),
    ("simklRecommendationToMeta", route_external_sync_simkl),
    ("simklScrobbleBody", route_external_sync_simkl),
    ("simklSyncApply", route_provider_library),
    ("simklSyncPlan", route_provider_library),
    ("simklWatchedToIds", route_external_sync_simkl),
    ("simklWatchingToItems", route_external_sync_simkl),
    ("simklWatchlistBody", route_external_sync_simkl),
    ("simklWatchlistRemovalRequest", route_external_sync_simkl),
    ("simklWatchlistRequest", route_external_sync_simkl),
    ("simklWatchlistToItems", route_external_sync_simkl),
    ("skipdbSegmentsPlan", route_intro_segments),
    ("skipdbSubmitPlan", route_intro_segments),
    ("stableFeedPart", route_content_identity),
    ("streamDiscoveryCacheKey", route_content_identity),
    ("streamDiscoveryCachePrefix", route_discovery_plan),
    ("streamDiscoveryEpisodeContext", route_content_identity),
    ("streamDiscoveryExecutionPolicy", route_discovery_plan),
    ("streamDiscoveryPlan", route_discovery_plan),
    ("streamMatchesEpisode", route_content_identity),
    ("streamPlaybackInfo", route_stream_policy),
    ("streamRequestHeaders", route_stream_policy),
    ("streamRequestIds", route_content_identity),
    ("streamRequestReferer", route_stream_policy),
    ("streamShellPlan", route_player_policy),
    ("streamSubtitlesResult", route_player_policy),
    ("stremioLibraryMutationPlan", route_external_sync_trakt),
    ("stremioWatchedToIds", route_external_sync_trakt),
    ("stremioWatchlistToItems", route_external_sync_trakt),
    ("subtitleLanguageMatches", route_stream_policy),
    ("subtitleTracks", route_addon_resource),
    ("supportsResource", route_addon_protocol),
    ("terminalRecommendationEligibility", route_library_state),
    ("terminalRecommendationPlan", route_library_state),
    ("theIntroDbMediaPlan", route_intro_segments),
    ("theIntroDbSubmitPlan", route_intro_segments),
    ("tmdbBuiltinCatalogUrl", route_tmdb),
    ("tmdbBuiltinManifest", route_tmdb),
    ("tmdbBuiltinMetaRequestPlan", route_tmdb),
    ("tmdbBuiltinMetaUrls", route_tmdb),
    ("tmdbBuiltinMetaUrlsFromFind", route_tmdb),
    ("tmdbBulkMetas", route_tmdb),
    ("tmdbBulkVideosToTrailers", route_tmdb),
    ("tmdbCollectionSourceUrl", route_tmdb),
    ("tmdbContentType", route_tmdb),
    ("tmdbCreditsUrlFromFind", route_tmdb),
    ("tmdbDetailRequestPlan", route_tmdb),
    ("tmdbDetailRequestUrlsFromFind", route_tmdb),
    ("tmdbEpisodesToVideos", route_tmdb),
    ("tmdbFullMetaToMeta", route_tmdb),
    ("tmdbImageUrl", route_tmdb),
    ("tmdbItemContentType", route_tmdb),
    ("tmdbLanguage", route_tmdb),
    ("tmdbMergeEnrichment", route_tmdb),
    ("tmdbMetaToMeta", route_tmdb),
    ("tmdbNumericId", route_content_identity),
    ("tmdbPeopleImagesFromCredits", route_tmdb),
    ("tmdbPeopleRequestPlan", route_tmdb),
    ("tmdbPickLogo", route_tmdb),
    ("tmdbRecommendationsUrl", route_tmdb),
    ("tmdbResolveIdHint", route_tmdb),
    ("tmdbSeasonRequestUrl", route_tmdb),
    ("tmdbVideoToTrailer", route_tmdb),
    ("toggleMetadataFeed", route_content_identity),
    ("toggleMetadataFeedLimited", route_content_identity),
    ("tokenMergePlan", route_profile_contract),
    ("torrentCacheLimitMb", route_device_resource),
    ("torrentFallbackFilePolicy", route_player_policy),
    ("torrentReadyBudget", route_stream_policy),
    ("torrentRetryPlan", route_stream_policy),
    ("torrentRuntimeInfo", route_stream_policy),
    ("torrentStatusInfo", route_stream_policy),
    ("trailerDirectSelection", route_trailer_subtitles),
    ("trailerPlaybackPolicy", route_trailer_subtitles),
    ("trailerSubtitleSelectionPlan", route_trailer_subtitles),
    ("trailerYoutubeVideoIds", route_trailer_subtitles),
    ("traktActivityDiff", route_external_sync_trakt),
    ("traktBearer", route_external_sync_trakt),
    ("traktCalendarPlan", route_provider_library),
    ("traktCollectionBody", route_external_sync_trakt),
    ("traktCommentsRequest", route_external_sync_trakt),
    ("traktContentIdFromIds", route_external_sync_trakt),
    ("traktEpisodeLocator", route_external_sync_trakt),
    ("traktHasClient", route_external_sync_trakt),
    ("traktHistoryRequest", route_external_sync_trakt),
    ("traktIdsFromContentId", route_external_sync_trakt),
    ("traktListReference", route_external_sync_trakt),
    ("traktMarkWatchedBody", route_external_sync_trakt),
    ("traktOAuthErrorCode", route_external_sync_trakt),
    ("traktPlaybackDeleteIds", route_external_sync_trakt),
    ("traktPlaybackItemsDedup", route_external_sync_trakt),
    ("traktPlaybackItemsToLibrary", route_external_sync_trakt),
    ("traktPlaybackUrl", route_external_sync_trakt),
    ("traktRelatedItemsToMetas", route_external_sync_trakt),
    ("traktRelatedLookupSlug", route_external_sync_trakt),
    ("traktRemapVideoIds", route_external_sync_trakt),
    ("traktScrobbleMediaId", route_external_sync_trakt),
    ("traktScrobblePlan", route_external_sync_trakt),
    ("traktScrobbleUrl", route_external_sync_trakt),
    ("traktShowIdFromEpisodeId", route_external_sync_trakt),
    ("traktSyncItemContentType", route_external_sync_trakt),
    ("traktSyncItemToMeta", route_external_sync_trakt),
    ("traktTokenExpiresAt", route_external_sync_trakt),
    ("traktUpNextToItems", route_external_sync_trakt),
    ("traktWatchedShowsToItems", route_external_sync_trakt),
    ("traktWatchedToIds", route_external_sync_trakt),
    ("traktWatchlistToItems", route_external_sync_trakt),
    ("uniqueIntroSegments", route_intro_segments),
    ("upsertStreamBadgeImport", route_stream_badges),
    ("valueMapDiff", route_library_state),
    ("versionIsNewer", route_version_policy),
    ("watchTogetherBuffering", route_watch_together),
    ("watchTogetherContent", route_watch_together),
    ("watchTogetherCreate", route_watch_together),
    ("watchTogetherDecode", route_watch_together),
    ("watchTogetherDriftCorrection", route_watch_together),
    ("watchTogetherJoin", route_watch_together),
    ("watchTogetherLeave", route_watch_together),
    ("watchTogetherPing", route_watch_together),
    ("watchTogetherPlaybackState", route_watch_together),
    ("watchTogetherRoomCodeSpec", route_watch_together),
    ("watchedMapDiff", route_library_state),
    ("watchedStateItems", route_library_state),
    ("watchedVideoIds", route_library_state),
    ("watchlistTogglePlan", route_watchlist),
];

#[cfg(test)]
mod tests {
    use super::METHODS;

    const SOURCES: &[&str] = &[
        include_str!("addon_protocol_routes.rs"),
        include_str!("addon_resource_routes.rs"),
        include_str!("addon_support_routes.rs"),
        include_str!("anime_nuvio_routes.rs"),
        include_str!("calendar_routes.rs"),
        include_str!("content_identity_routes.rs"),
        include_str!("content_warning_routes.rs"),
        include_str!("core_addon_store_routes.rs"),
        include_str!("device_auth_routes.rs"),
        include_str!("discord_presence_routes.rs"),
        include_str!("engine_routes.rs"),
        include_str!("external_sync_routes.rs"),
        include_str!("fluxa_sync_routes.rs"),
        include_str!("intro_plugins_routes.rs"),
        include_str!("library_routes.rs"),
        include_str!("local_media_routes.rs"),
        include_str!("mdblist_routes.rs"),
        include_str!("plan_misc_routes.rs"),
        include_str!("player_policy_routes.rs"),
        include_str!("player_scrobble_routes.rs"),
        include_str!("profile_routes.rs"),
        include_str!("provider_library_routes.rs"),
        include_str!("publicmetadb_routes.rs"),
        include_str!("resource_plan_routes.rs"),
        include_str!("search_plan_routes.rs"),
        include_str!("stream_badge_routes.rs"),
        include_str!("stream_policy_routes.rs"),
        include_str!("tmdb_routes.rs"),
        include_str!("version_policy_routes.rs"),
        include_str!("watch_together_routes.rs"),
        include_str!("watchlist_offline_routes.rs"),
        include_str!("../library/local_media.rs"),
    ];

    fn arm_methods(line: &str) -> Vec<&str> {
        let Some(rest) = line.strip_prefix("        ") else {
            return Vec::new();
        };
        let mut rest = rest.strip_prefix("| ").unwrap_or(rest);
        let mut found = Vec::new();
        while let Some(body) = rest.strip_prefix('"') {
            let Some(end) = body.find('"') else {
                return Vec::new();
            };
            found.push(&body[..end]);
            rest = &body[end + 1..];
            match rest.strip_prefix(" | ") {
                Some(next) if next.starts_with('"') => rest = next,
                _ => break,
            }
        }
        match rest.trim_end() {
            "" | " |" => found,
            tail if tail.starts_with(" =>") => found,
            _ => Vec::new(),
        }
    }

    #[test]
    fn table_lists_every_router_arm() {
        let mut arms = Vec::new();
        for source in SOURCES {
            let mut in_router = false;
            for line in source.lines() {
                if line.contains(" fn route") && line.contains("(method: &str") {
                    in_router = true;
                } else if line.starts_with('}') {
                    in_router = false;
                } else if in_router {
                    arms.extend(arm_methods(line));
                }
            }
        }
        arms.sort_unstable();
        let names = METHODS.iter().map(|(name, _)| *name).collect::<Vec<_>>();
        assert!(names.windows(2).all(|pair| pair[0] < pair[1]));
        assert_eq!(arms, names);
    }
}
