import type { RefObject } from 'react';
import type { PlayerTrackOption } from '../../core/mpvPlayer';
import { TrackPopover } from './TrackPopover';
import type { PlayerTrackPopover } from './usePlayerTrackControls';
import type { usePlayerSubtitleControls } from './usePlayerSubtitleControls';

export function PlayerTrackPanel({ type, audioTracks, subTracks, playbackSpeed, refs, onClose, onSetSpeed, onSelectTrack, onDisableSubs, subtitleControls }: { type: Exclude<PlayerTrackPopover, null>; audioTracks: PlayerTrackOption[]; subTracks: PlayerTrackOption[]; playbackSpeed: number; refs: { audio: RefObject<HTMLButtonElement | null>; sub: RefObject<HTMLButtonElement | null>; speed: RefObject<HTMLButtonElement | null> }; onClose: () => void; onSetSpeed: (speed: number) => void; onSelectTrack: (type: 'audio' | 'sub', id: string) => void; onDisableSubs: () => void; subtitleControls: ReturnType<typeof usePlayerSubtitleControls> }) {
  return <TrackPopover type={type} audioTracks={audioTracks} subTracks={subTracks} playbackSpeed={playbackSpeed} anchorRef={type === 'audio' ? refs.audio : type === 'sub' ? refs.sub : refs.speed} onClose={onClose} onSetSpeed={onSetSpeed} onSelectTrack={onSelectTrack} onDisableSubs={onDisableSubs} subtitleDelay={subtitleControls.subtitleDelay} subtitlePosition={subtitleControls.subtitlePosition} subtitleFont={subtitleControls.subtitleFont} subtitleSize={subtitleControls.subtitleSize} subtitleColor={subtitleControls.subtitleColor} subtitleTextOpacity={subtitleControls.subtitleTextOpacity} subtitleBackgroundColor={subtitleControls.subtitleBackgroundColor} subtitleBackgroundOpacity={subtitleControls.subtitleBackgroundOpacity} subtitleOutlineColor={subtitleControls.subtitleOutlineColor} subtitleOutlineOpacity={subtitleControls.subtitleOutlineOpacity} subtitleForceStyle={subtitleControls.subtitleForceStyle} subtitleCharacterEdge={subtitleControls.subtitleCharacterEdge} subtitleShadow={subtitleControls.subtitleShadow} onAdjustSubtitleDelay={subtitleControls.adjustSubtitleDelay} onChooseSubtitlePosition={subtitleControls.chooseSubtitlePosition} onResetSubtitleDelay={subtitleControls.resetSubtitleDelay} autoSyncing={subtitleControls.autoSyncingSubtitles} onAutoSyncSubtitles={() => { void subtitleControls.autoSyncSubtitles(); }} subtitleCaptureCues={subtitleControls.subtitleCaptureCues} onApplySubtitleCapture={subtitleControls.applySubtitleCapture} onChooseSubtitleFont={subtitleControls.chooseSubtitleFont} onChooseSubtitleSize={subtitleControls.chooseSubtitleSize} onAdjustSubtitleSize={subtitleControls.adjustSubtitleSize} onChooseSubtitleColor={subtitleControls.chooseSubtitleColor} onChooseSubtitleStyle={subtitleControls.chooseSubtitleStyle} />;
}
