[versions]
androidGradlePlugin = "8.13.2"
kotlin = "2.3.20"
coreKtx = "1.18.0"
coroutines = "1.11.0"
mpv = "1.0.0"
okhttp = "5.4.0"
benchmark = "1.4.1"
uiautomator = "2.4.0"
androidxTestRunner = "1.6.2"
androidxTestJunit = "1.2.1"

[libraries]
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
mpv = { group = "dev.jdtech.mpv", name = "libmpv", version.ref = "mpv" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
gson = { group = "com.google.code.gson", name = "gson", version = "2.13.1" }

androidx-benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "benchmark" }
androidx-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTestRunner" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestJunit" }

[bundles]
coroutines = ["kotlinx-coroutines-core", "kotlinx-coroutines-android"]

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-test = { id = "com.android.test", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
fluxa-android-application = { id = "fluxa.android.application" }
fluxa-android-rust = { id = "fluxa.android.rust" }
