import type React from 'react';
import { color, fade, fontSize, heading, layout, lineHeight, radius, space, tracking, weight, z } from '../../design';

export const NAV_RAIL_WIDTH = 6.5;
export const TOP_BAR_H = 3.25;

export const spinnerStyle: React.CSSProperties = {
  width: '2rem',
  height: '2rem',
  border: `0.1875rem solid ${color.lineStrong}`,
  borderTopColor: color.outline,
  borderRadius: radius.circle,
  animation: 'spin 0.8s linear infinite',
};

export const S: Record<string, React.CSSProperties> = {
  screen: { position: 'relative', width: '100%', height: '100%', background: color.bgElevated, display: 'flex', overflow: 'hidden' },
  bgWrap: { position: 'absolute', inset: 0, zIndex: 0 },
  bgImg: { width: '100%', height: '100%', objectFit: 'cover', objectPosition: 'center top', opacity: 0.36 },
  bgGradLeft: {
    position: 'absolute',
    inset: 0,
    background: `linear-gradient(to right, ${fade.elevated(0.98)} 0%, ${fade.elevated(0.78)} 48%, ${fade.elevated(0.9)} 100%)`,
  },
  bgGradBottom: {
    position: 'absolute',
    inset: 0,
    background: `linear-gradient(to bottom, transparent 30%, ${fade.elevated(0.92)} 85%, ${color.bgElevated} 100%)`,
  },
  leftPanel: {
    flex: 1,
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    position: 'relative',
    zIndex: 1,
    overflow: 'hidden',
    paddingTop: `${TOP_BAR_H}rem`,
  },
  scrollArea: { flex: 1, overflowY: 'auto', scrollbarWidth: 'none', padding: `1.625rem 2.125rem 1.5rem ${NAV_RAIL_WIDTH + 2.625}rem` },
  backBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.25rem',
    background: color.fill,
    border: `1px solid ${color.line}`,
    color: color.textStrong,
    fontSize: fontSize.base,
    fontWeight: 600,
    cursor: 'pointer',
    padding: '0.4375rem 0.875rem',
    borderRadius: radius.md,
  },
  logo: { height: '7.375rem', maxWidth: '28.125rem', objectFit: 'contain', objectPosition: 'left center' },
  titleText: { color: color.textPrimary, fontSize: fontSize.hero, fontWeight: 900, margin: 0, lineHeight: 1.05, letterSpacing: '-0.0313rem' },
  metaLine: { color: color.textBody, fontSize: fontSize.md, fontWeight: 600, margin: 0 },
  imdbBadge: { display: 'inline-flex', alignItems: 'center', gap: '0.375rem', flexShrink: 0 },
  imdbBadgeCompact: { gap: '0.25rem' },
  imdbLogo: {
    display: 'inline-flex',
    alignItems: 'center',
    height: '1.0625rem',
    padding: '0 0.25rem',
    borderRadius: radius.xs,
    background: color.imdb,
    color: color.onLight,
    fontSize: fontSize.micro,
    fontWeight: 900,
    lineHeight: 1,
  },
  imdbLogoCompact: { height: '0.875rem', padding: '0 0.1875rem', fontSize: fontSize.micro },
  imdbRating: { color: color.textStrong, fontSize: fontSize.sm, fontWeight: 700 },
  imdbRatingCompact: { fontSize: fontSize.micro },
  genrePill: {
    color: color.textBody,
    fontSize: fontSize.base,
    fontWeight: 600,
    padding: '0.25rem 0.75rem',
    border: `1px solid ${color.lineStrong}`,
    borderRadius: radius.pill,
    whiteSpace: 'nowrap',
  },
  sectionLabel: {
    color: color.textDim,
    fontSize: fontSize.xs,
    fontWeight: 800,
    letterSpacing: '0.05rem',
    textTransform: 'uppercase',
    margin: '0 0 0.625rem',
  },
  descText: { color: color.textBody, fontSize: fontSize.md, lineHeight: '1.375rem', margin: 0, maxWidth: '31.25rem' },
  awardsText: {
    color: color.textMuted,
    fontSize: fontSize.base,
    lineHeight: '1.25rem',
    margin: 0,
    maxWidth: '31.25rem',
    fontWeight: 600,
  },
  castRow: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '0.75rem',
    overflowX: 'auto',
    scrollbarWidth: 'none',
    paddingBottom: '0.75rem',
  },
  similarSection: { position: 'relative', zIndex: 1, padding: '0.5rem 0 1.875rem' },
  similarTitle: { color: color.textPrimary, fontSize: fontSize.xl, lineHeight: '1.5rem', fontWeight: 900, margin: '0 0 0.875rem' },
  similarRow: {
    display: 'flex',
    gap: '1rem',
    overflowX: 'auto',
    overflowY: 'hidden',
    scrollbarWidth: 'none',
    padding: '0.625rem 0 1.5rem',
  },
  actionBar: {
    flexShrink: 0,
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: '0.5rem',
    padding: `0.875rem 2.125rem 1.125rem ${NAV_RAIL_WIDTH + 2.625}rem`,
    borderTop: `1px solid ${color.line}`,
    background: color.bgElevated,
  },
  playBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    height: '2.625rem',
    minWidth: '6.875rem',
    background: color.light,
    color: color.onLight,
    border: 'none',
    borderRadius: radius.md,
    fontSize: fontSize.md,
    fontWeight: 900,
    cursor: 'pointer',
    paddingLeft: '1.125rem',
    paddingRight: '1.125rem',
    flexShrink: 0,
  },
  secondaryBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    height: '2.625rem',
    padding: '0 1rem',
    background: 'transparent',
    color: color.textStrong,
    border: `1px solid ${color.lineStrong}`,
    borderRadius: radius.md,
    fontSize: fontSize.base,
    fontWeight: 700,
    cursor: 'pointer',
    flexShrink: 0,
    transition: 'background 0.15s',
  },
};

export const EP: Record<string, React.CSSProperties> = {
  panel: {
    width: 'min(48vw, 32.5rem)',
    minWidth: '28.75rem',
    height: `calc(100% - ${TOP_BAR_H + 1.5}rem)`,
    alignSelf: 'flex-start',
    marginTop: `${TOP_BAR_H + 0.625}rem`,
    marginRight: '0.875rem',
    marginBottom: '0.875rem',
    flexShrink: 0,
    background: fade.ground(0.92),
    backdropFilter: 'blur(0.5rem)',
    border: `1px solid ${color.line}`,
    borderRadius: radius.lg,
    display: 'flex',
    flexDirection: 'column',
    position: 'relative',
    zIndex: 1,
    overflow: 'hidden',
    paddingTop: 0,
    boxShadow: `0 0.5rem 1.5rem ${fade.shade(0.35)}`,
  },
  seasonNav: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '0.8125rem 1rem',
    borderBottom: `1px solid ${color.line}`,
    gap: '0.5rem',
  },
  navBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.25rem',
    background: 'transparent',
    border: 'none',
    color: color.textBody,
    fontSize: fontSize.sm,
    fontWeight: 600,
    cursor: 'pointer',
    padding: '0.25rem 0.5rem',
    borderRadius: radius.sm,
    flexShrink: 0,
  },
  seasonBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.375rem',
    background: color.fill,
    border: `1px solid ${color.line}`,
    color: color.textPrimary,
    fontSize: fontSize.base,
    fontWeight: 700,
    cursor: 'pointer',
    padding: '0.375rem 0.75rem',
    borderRadius: radius.md,
  },
  seasonMenu: {
    position: 'absolute',
    top: 'calc(100% + 0.375rem)',
    right: 0,
    background: color.surface,
    border: `1px solid ${color.lineStrong}`,
    borderRadius: radius.md,
    padding: space[1],
    display: 'flex',
    flexDirection: 'column',
    zIndex: z.dialog,
    minWidth: '9.5rem',
    boxShadow: `0 0.5rem 1.5rem ${fade.shade(0.5)}`,
  },
  seasonMenuItem: {
    width: '100%',
    textAlign: 'left',
    padding: `${space[2]} ${space[2.5]}`,
    border: 'none',
    borderRadius: radius.sm,
    cursor: 'pointer',
    fontSize: fontSize.sm,
    color: color.textBody,
    transition: 'background 0.12s',
  },
  searchRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.625rem',
    padding: '0.6875rem 1rem',
    borderBottom: `1px solid ${color.line}`,
  },
  searchInput: {
    flex: 1,
    background: 'transparent',
    border: 'none',
    outline: 'none',
    color: color.textBody,
    fontSize: fontSize.base,
    padding: 0,
  },
  list: { flex: 1, overflowY: 'auto', scrollbarWidth: 'thin', scrollbarColor: `${color.fillHover} transparent` },
  row: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '0.8125rem',
    padding: '0.6875rem 1rem',
    cursor: 'pointer',
    borderBottom: `1px solid ${color.line}`,
    transition: 'background 0.15s',
  },
  thumb: {
    width: '9.625rem',
    height: '5.375rem',
    borderRadius: radius.md,
    overflow: 'hidden',
    flexShrink: 0,
    background: color.fill,
    position: 'relative',
  },
  thumbPlaceholder: { width: '100%', height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center' },
  thumbOverlay: {
    position: 'absolute',
    inset: 0,
    background: fade.shade(0.45),
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  watchedBadge: {
    position: 'absolute',
    top: '0.3125rem',
    left: '0.3125rem',
    background: color.imdb,
    color: color.onLight,
    fontSize: fontSize.micro,
    fontWeight: 900,
    padding: '0.125rem 0.3125rem',
    borderRadius: radius.xs,
  },
  epTitle: {
    color: color.textPrimary,
    fontSize: fontSize.base,
    fontWeight: 700,
    margin: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    flex: 1,
    minWidth: 0,
  },
  epDate: { color: color.textDim, fontSize: fontSize.xs, margin: 0, flexShrink: 0, whiteSpace: 'nowrap' },
  epMetaRight: { display: 'flex', alignItems: 'center', gap: '0.4375rem', flexShrink: 0 },
  epDesc: {
    color: color.textMuted,
    fontSize: fontSize.sm,
    lineHeight: '1.0625rem',
    margin: 0,
    display: '-webkit-box',
    WebkitLineClamp: 3,
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
  },
  empty: { padding: '1.5rem 0.875rem', color: color.textDim, fontSize: fontSize.base },
  inlineSources: {
    flex: 1,
    overflowY: 'auto',
    padding: '0.8125rem 1rem 1.5rem',
    background: color.black,
    scrollbarWidth: 'thin',
    scrollbarColor: `${color.fillHover} transparent`,
  },
  backToEpisodesBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.4375rem',
    height: '2.125rem',
    padding: '0 0.6875rem',
    borderRadius: radius.pill,
    border: `1px solid ${color.line}`,
    background: color.fill,
    color: color.textPrimary,
    fontSize: fontSize.sm,
    fontWeight: 800,
    cursor: 'pointer',
    marginBottom: '0.875rem',
  },
  sourceHeader: { paddingBottom: '0.875rem', borderBottom: `1px solid ${color.line}`, marginBottom: '0.75rem' },
  sourceKicker: {
    color: color.textDim,
    fontSize: fontSize.xs,
    fontWeight: 900,
    margin: '0 0 0.3125rem',
    textTransform: 'uppercase',
    letterSpacing: '0.05rem',
  },
  sourceTitle: { color: color.textPrimary, fontSize: fontSize.xl, lineHeight: '1.4375rem', fontWeight: 900, margin: 0 },
  sourceSubtitle: { color: color.textMuted, fontSize: fontSize.sm, fontWeight: 700, margin: '0.375rem 0 0' },
  sourcePills: { display: 'flex', gap: '0.5rem', overflowX: 'auto', padding: '0 0 0.75rem', scrollbarWidth: 'none' },
  inlineStreamList: { display: 'flex', flexDirection: 'column', gap: '0.5625rem', paddingBottom: '0.625rem' },
};

export const SS: Record<string, React.CSSProperties> = {
  screen: { position: 'relative', width: '100%', height: '100%', background: color.black, overflow: 'hidden' },
  hero: { position: 'absolute', top: 0, left: 0, right: 0, height: '18.75rem', overflow: 'hidden', opacity: 0.86 },
  heroImg: { width: '100%', height: '100%', objectFit: 'cover', objectPosition: 'center' },
  heroFade: {
    position: 'absolute',
    inset: 0,
    background: `linear-gradient(to bottom, ${fade.shade(0.12)} 0%, ${fade.shade(0.72)} 56%, ${color.black} 100%)`,
  },
  backBtn: {
    position: 'fixed',
    top: `${TOP_BAR_H + 1}rem`,
    left: `${NAV_RAIL_WIDTH + 1}rem`,
    width: '2.75rem',
    height: '2.75rem',
    zIndex: z.sticky,
    border: 'none',
    borderRadius: radius.circle,
    background: fade.shade(0.5),
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    backdropFilter: 'blur(0.5rem)',
  },
  content: {
    position: 'relative',
    zIndex: 1,
    height: '100%',
    overflowY: 'auto',
    padding: `${TOP_BAR_H + 5}rem 3.625rem 2.625rem ${NAV_RAIL_WIDTH + 3.625}rem`,
  },
  header: { maxWidth: '47.5rem', paddingTop: '4.625rem', paddingBottom: '1.375rem' },
  kicker: {
    color: color.textMuted,
    fontSize: fontSize.base,
    fontWeight: 800,
    margin: '0 0 0.5rem',
    textTransform: 'uppercase',
    letterSpacing: '0.05rem',
  },
  title: { color: color.textPrimary, fontSize: fontSize.h1, lineHeight: '2.875rem', fontWeight: 900, margin: 0 },
  epLine: { color: color.textBody, fontSize: fontSize.lg, fontWeight: 700, margin: '0.625rem 0 0' },
  filterRow: { display: 'flex', gap: '0.5rem', overflowX: 'auto', padding: '0 0 1.125rem', scrollbarWidth: 'none' },
  pill: {
    display: 'inline-flex',
    alignItems: 'center',
    height: '2.125rem',
    padding: '0 0.875rem',
    borderRadius: radius.pill,
    background: color.light,
    color: color.onLight,
    fontSize: fontSize.sm,
    fontWeight: 800,
    whiteSpace: 'nowrap',
  },
  pillMuted: {
    display: 'inline-flex',
    alignItems: 'center',
    height: '2.125rem',
    padding: '0 0.875rem',
    borderRadius: radius.pill,
    background: color.fillHover,
    color: color.textPrimary,
    fontSize: fontSize.sm,
    fontWeight: 800,
    whiteSpace: 'nowrap',
  },
  center: { display: 'flex', justifyContent: 'center', padding: '2.25rem 0' },
  emptyText: { color: color.textMuted, fontSize: fontSize.md, margin: 0 },
  streamList: { display: 'flex', flexDirection: 'column', gap: '0.625rem', maxWidth: '53.75rem', paddingBottom: '1.875rem' },
  streamRow: {
    width: '100%',
    maxWidth: '100%',
    minWidth: 0,
    boxSizing: 'border-box',
    border: `1px solid ${color.line}`,
    borderRadius: radius.md,
    minHeight: '5.75rem',
    padding: '0.8125rem 0.875rem',
    textAlign: 'left',
    cursor: 'pointer',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: '0.375rem',
    transition: 'background 0.15s, color 0.15s',
    overflow: 'hidden',
  },
  streamName: {
    color: color.textPrimary,
    maxWidth: '100%',
    minWidth: 0,
    fontSize: fontSize.base,
    lineHeight: '1.125rem',
    fontWeight: 900,
    overflow: 'hidden',
    display: 'block',
    overflowWrap: 'anywhere',
    wordBreak: 'break-word',
    whiteSpace: 'pre-wrap',
  },
  streamAddon: {
    maxWidth: '100%',
    minWidth: 0,
    fontSize: fontSize.xs,
    lineHeight: '0.875rem',
    fontWeight: 700,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  streamDesc: {
    color: color.textBody,
    maxWidth: '100%',
    minWidth: 0,
    fontSize: fontSize.xs,
    lineHeight: '1rem',
    overflow: 'visible',
    display: 'block',
    overflowWrap: 'anywhere',
    wordBreak: 'break-word',
    whiteSpace: 'pre-wrap',
  },
  torrentTag: {
    maxWidth: '100%',
    marginTop: '0.125rem',
    alignSelf: 'flex-start',
    background: color.fillHover,
    fontSize: fontSize.micro,
    lineHeight: '0.75rem',
    fontWeight: 700,
    padding: '0.125rem 0.4375rem',
    borderRadius: radius.xs,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
};

export const MS: Record<string, React.CSSProperties> = {
  screen: {
    position: 'relative',
    width: '100%',
    height: '100%',
    background: color.bgElevated,
    overflowY: 'auto',
    overflowX: 'hidden',
    scrollbarWidth: 'none',
  },
  pageBgWrap: { position: 'fixed', inset: 0, zIndex: 0, overflow: 'hidden', background: color.bgElevated },
  pageBgImg: { width: '100%', height: '100%', objectFit: 'cover', objectPosition: 'center top', transition: 'opacity 0.3s ease' },
  pageBgGradLeft: {
    position: 'absolute',
    inset: 0,
    background: `linear-gradient(to right, ${fade.elevated(0.92)} 0%, ${fade.elevated(0.5)} 32%, ${fade.elevated(0.12)} 58%, transparent 100%)`,
  },
  pageBgGradBottom: {
    position: 'absolute',
    inset: 0,
    background:
      `linear-gradient(to bottom, transparent 0%, ${fade.elevated(0.12)} 40%, ${fade.elevated(0.45)} 62%, ${fade.elevated(0.85)} 80%, ${color.bgElevated} 92%)`,
  },
  heroWrap: {
    position: 'relative',
    width: '100%',
    height: '46vh',
    minHeight: '22rem',
    maxHeight: '34rem',
    overflow: 'hidden',
    flexShrink: 0,
    zIndex: 1,
  },
  heroPlaceholder: { position: 'fixed', inset: 0, zIndex: 0, background: color.bgElevated },
  heroTrailerContainer: { position: 'absolute', inset: 0 },
  heroTrailerFrame: {
    position: 'absolute',
    inset: 0,
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    border: 'none',
    pointerEvents: 'none',
  },
  trailerOverlayWrap: { position: 'fixed', inset: 0, zIndex: 5, pointerEvents: 'none' },
  heroTrailerSubtitleOverlay: {
    position: 'absolute',
    left: '50%',
    bottom: '12rem',
    transform: 'translateX(-50%)',
    maxWidth: 'min(42rem, calc(100% - 10rem))',
    padding: '0.2rem 0.55rem',
    borderRadius: radius.xs,
    background: fade.shade(0.58),
    color: color.textPrimary,
    fontSize: 'clamp(0.75rem, 1.1vw, 1rem)',
    fontWeight: 700,
    lineHeight: 1.25,
    textAlign: 'center',
    textShadow: `0 0.125rem 0.25rem ${fade.shade(0.9)}`,
    whiteSpace: 'pre-line',
    pointerEvents: 'none',
  },
  heroTrailerMuteButton: {
    position: 'absolute',
    bottom: '1.25rem',
    right: '1.5rem',
    width: '2.375rem',
    height: '2.375rem',
    borderRadius: radius.circle,
    background: fade.shade(0.45),
    border: `1px solid ${color.lineStrong}`,
    color: color.textPrimary,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    padding: 0,
    transition: 'background 0.2s ease, border-color 0.2s ease',
  },
  heroTrailerProgressTrack: {
    position: 'absolute',
    bottom: '1.25rem',
    left: '4.6875rem',
    width: '13.75rem',
    height: '0.1875rem',
    borderRadius: radius.pill,
    background: color.fillStrong,
    overflow: 'hidden',
  },
  heroTrailerProgressFill: { display: 'block', height: '100%', background: color.light, borderRadius: radius.pill },
  heroTrailerFullscreenButton: {
    position: 'absolute',
    top: `${TOP_BAR_H + 0.875}rem`,
    right: '4.6875rem',
    width: '2.375rem',
    height: '2.375rem',
    borderRadius: radius.circle,
    background: fade.shade(0.52),
    backdropFilter: 'blur(0.5rem)',
    border: `1px solid ${color.lineStrong}`,
    color: color.textStrong,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    padding: 0,
  },
  backBtn: {
    position: 'absolute',
    top: `${TOP_BAR_H + 0.875}rem`,
    right: '2.5rem',
    width: '2.375rem',
    height: '2.375rem',
    borderRadius: radius.circle,
    background: fade.shade(0.52),
    backdropFilter: 'blur(0.5rem)',
    border: `1px solid ${color.lineStrong}`,
    color: color.textStrong,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    zIndex: z.sticky,
    padding: 0,
  },
  logoWrap: {
    position: 'absolute',
    bottom: '6rem',
    left: '4.6875rem',
    zIndex: 5,
    display: 'flex',
    flexDirection: 'column',
    gap: space[3],
    alignItems: 'flex-start',
  },
  logo: {
    height: '6.5rem',
    maxWidth: '26rem',
    objectFit: 'contain',
    objectPosition: 'left center',
    filter: `drop-shadow(0 0.125rem 1.125rem ${fade.shade(0.8)})`,
  },
  titleHero: {
    ...heading('hero'),
    color: color.textPrimary,
    textShadow: `0 0.125rem 1.375rem ${fade.shade(0.8)}`,
  },
  content: {
    position: 'relative',
    zIndex: 1,
    padding: '1.5rem 3.75rem 3.75rem 4.6875rem',
    marginTop: '-5rem',
    background: `linear-gradient(to bottom, transparent 0rem, ${fade.elevated(0.4)} 5rem, ${fade.elevated(0.88)} 11rem, ${color.bgElevated} 16rem)`,
    display: 'flex',
    flexDirection: 'column',
    gap: '1.125rem',
  },
  factGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(16rem, max-content))',
    gap: `${space[2]} ${space[10]}`,
  },
  factRow: { display: 'flex', alignItems: 'baseline', gap: space[3] },
  factKey: { fontSize: fontSize.base, color: color.textDim, fontWeight: weight.medium, minWidth: '5.5rem' },
  factValue: { fontSize: fontSize.base, color: color.textStrong, fontWeight: weight.semibold },
  scoreRow: { display: 'flex', flexWrap: 'wrap', gap: space[4] },
  scoreItem: { fontSize: fontSize.base, color: color.textStrong, fontWeight: weight.semibold },
  sectionHeaderRow: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: space[4], margin: '0 0 0.875rem' },
  heroProgressRow: { display: 'flex', alignItems: 'center', gap: space[3] },
  heroProgressTrack: {
    width: '13rem',
    height: '0.1875rem',
    borderRadius: radius.pill,
    background: color.fillStrong,
    overflow: 'hidden',
  },
  heroProgressFill: { display: 'block', height: '100%', background: color.accent },
  heroProgressLabel: { fontSize: fontSize.sm, color: color.textMuted, fontVariantNumeric: 'tabular-nums' },
  metaChipRow: { display: 'flex', alignItems: 'center', gap: space[2.5], flexWrap: 'wrap' },
  actionRow: { display: 'flex', alignItems: 'center', gap: '1rem' },
  actionIcons: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.125rem',
    height: '3.125rem',
    padding: '0 0.375rem',
    borderRadius: radius.md,
    background: fade.tint(0.06),
  },
  playBtn: {
    display: 'flex',
    alignItems: 'center',
    height: '3.125rem',
    minWidth: '9.25rem',
    background: color.light,
    color: color.onLight,
    border: 'none',
    borderRadius: radius.md,
    fontSize: fontSize.md,
    fontWeight: 700,
    cursor: 'pointer',
    padding: '0 1.5rem',
    flexShrink: 0,
    transition: 'background 0.15s',
  },
  metaBlock: { maxWidth: '41.25rem', marginBottom: '0.5rem' },
  metaInfoLine: { color: color.textDim, fontSize: fontSize.base, fontWeight: 500, margin: '0 0 0.75rem', lineHeight: '1.25rem' },
  genreTag: { color: color.textBody, fontWeight: 600, fontSize: fontSize.base, textDecoration: 'none', cursor: 'pointer' },
  metaDot: { color: color.textFaint, margin: '0 0.1875rem' },
  metaDetailsText: { color: color.textDim },
  descText: {
    color: color.textBody,
    fontSize: fontSize.md,
    lineHeight: '1.5625rem',
    margin: '0 0 0.75rem',
    display: '-webkit-box',
    WebkitLineClamp: 3,
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
  },
  seasonRowModern: { display: 'flex', alignItems: 'center', gap: '0.625rem', marginBottom: '0.5rem' },
  seasonBtn: {
    height: '2rem',
    background: color.fill,
    border: `1px solid ${color.line}`,
    color: color.textPrimary,
    fontSize: fontSize.sm,
    fontWeight: weight.semibold,
    padding: `0 ${space[2.5]}`,
    borderRadius: radius.md,
    gap: space[1.5],
  },
  seasonWatchedBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '2rem',
    height: '2rem',
    background: color.fill,
    border: `1px solid ${color.line}`,
    padding: 0,
    cursor: 'pointer',
    borderRadius: radius.md,
  },
  seasonWatchedLabel: { color: color.textBody, fontSize: fontSize.base, fontWeight: 600 },
  tabRow: {
    display: 'flex',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    gap: space[4],
    borderBottom: `1px solid ${color.line}`,
  },
  tabTrailing: { display: 'flex', alignItems: 'center', gap: space[1.5], paddingBottom: space[2] },
  tabBar: { display: 'flex' },
  tabBtn: {
    background: 'transparent',
    borderTop: 'none',
    borderLeft: 'none',
    borderRight: 'none',
    borderBottomWidth: '0.125rem',
    borderBottomStyle: 'solid',
    borderBottomColor: 'transparent',
    outline: 'none',
    appearance: 'none',
    WebkitAppearance: 'none',
    color: color.textDim,
    fontSize: fontSize.md,
    fontWeight: 600,
    cursor: 'pointer',
    padding: '0.625rem 1.25rem 0.625rem 0',
    marginBottom: '-0.0625rem',
    marginRight: '0.25rem',
  },
  tabBtnActive: { color: color.textPrimary, borderBottomColor: color.light },
  episodeSection: { paddingBottom: '3rem' },
  episodeCount: { color: color.textMuted, fontSize: fontSize.base, fontWeight: 500, margin: '0 0 1.125rem' },
  episodeGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(min(21rem, 100%), 1fr))', gap: '1.875rem 1.25rem' },
  epCard: { cursor: 'pointer', display: 'flex', flexDirection: 'column' },
  epThumb: {
    position: 'relative',
    width: '100%',
    aspectRatio: '16 / 9',
    borderRadius: radius.md,
    overflow: 'hidden',
    background: color.fill,
    marginBottom: '0.625rem',
    flexShrink: 0,
  },
  epThumbPlaceholder: { width: '100%', height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center' },
  epTimeRemaining: {
    position: 'absolute',
    bottom: '0.5rem',
    right: '0.5rem',
    background: fade.shade(0.76),
    color: color.textPrimary,
    fontSize: fontSize.xs,
    fontWeight: 700,
    padding: '0.125rem 0.4375rem',
    borderRadius: radius.xs,
  },
  epProgressTrack: { position: 'absolute', bottom: 0, left: 0, right: 0, height: '0.1875rem', background: fade.shade(0.55) },
  epProgressFill: { height: '100%', borderRadius: `0 ${radius.xs} ${radius.xs} 0` },
  epHoverOverlay: {
    position: 'absolute',
    inset: 0,
    background: fade.shade(0.4),
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  epTitle: { color: color.textPrimary, fontSize: fontSize.md, fontWeight: 700, margin: '0 0 0.3125rem', lineHeight: '1.1875rem' },
  epDesc: {
    color: color.textBody,
    fontSize: fontSize.base,
    lineHeight: '1.1875rem',
    margin: '0 0 0.5rem',
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
  },
  epMetaRow: { display: 'flex', alignItems: 'center', gap: '0.5rem', flexWrap: 'wrap' },
  epRatingBadge: {
    border: `1px solid ${color.outline}`,
    borderRadius: radius.xs,
    color: color.textMuted,
    fontSize: fontSize.xs,
    fontWeight: 700,
    padding: '0.125rem 0.375rem',
    flexShrink: 0,
  },
  epMetaText: { color: color.textBody, fontSize: fontSize.sm, fontWeight: 500 },
  similarSourcePicker: { position: 'relative', display: 'flex', justifyContent: 'flex-end', zIndex: z.sticky },
  similarSourceButton: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: space[1.5],
    height: '2rem',
    border: `1px solid ${color.line}`,
    borderRadius: radius.md,
    background: color.fill,
    color: color.textPrimary,
    padding: `0 ${space[2.5]}`,
    fontSize: fontSize.sm,
    fontWeight: weight.semibold,
    cursor: 'pointer',
  },
  similarSourceMenu: {
    position: 'absolute',
    top: 'calc(100% + 0.375rem)',
    right: 0,
    minWidth: '13.5rem',
    padding: space[1],
    border: `1px solid ${color.lineStrong}`,
    borderRadius: radius.md,
    background: color.surface,
    boxShadow: `0 0.5rem 1.5rem ${fade.shade(0.5)}`,
    display: 'flex',
    flexDirection: 'column',
    gap: '0.125rem',
  },
  similarSourceMenuItem: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    minHeight: '2.25rem',
    border: 'none',
    borderRadius: radius.md,
    background: 'transparent',
    color: color.textBody,
    padding: '0.375rem 0.625rem',
    textAlign: 'left',
    fontSize: fontSize.base,
    fontWeight: 650,
    cursor: 'pointer',
  },
  similarSourceMenuItemActive: { background: color.fillHover, color: color.textPrimary },
  relatedSection: { paddingBottom: '3rem' },
  relatedGrid: { display: 'flex', gap: '1rem', overflowX: 'auto', overflowY: 'hidden', scrollbarWidth: 'none', paddingBottom: '0.5rem' },
  detailsTab: { paddingBottom: 0 },
  detailsSection: { marginBottom: '2.25rem' },
  detailsSectionTitle: {
    color: color.textPrimary,
    flexShrink: 0,
    fontSize: fontSize.xl,
    fontWeight: weight.bold,
    letterSpacing: '-0.01em',
    lineHeight: 1.2,
    margin: '0 0 0.875rem',
  },
  detailsText: { color: color.textBody, fontSize: fontSize.md, lineHeight: '1.375rem', margin: 0, maxWidth: '56.25rem' },
  overlayBackdrop: {
    position: 'fixed',
    inset: 0,
    background: fade.shade(0.74),
    backdropFilter: 'blur(0.5rem)',
    zIndex: z.dialog,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '2.5rem',
  },
  overlaySheet: {
    background: color.black,
    borderRadius: radius.xl,
    border: `1px solid ${color.line}`,
    width: '100%',
    maxWidth: '35rem',
    maxHeight: '80vh',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    boxShadow: `0 0.75rem 2rem ${fade.shade(0.5)}`,
  },
  overlayCloseBtn: {
    width: '2.125rem',
    height: '2.125rem',
    borderRadius: radius.circle,
    background: color.fillHover,
    border: 'none',
    color: color.textBody,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    padding: 0,
    flexShrink: 0,
  },
};
