import type React from 'react';
import { color, fade, font, fontSize, heading, layout, radius } from '../../design/tokens';

export const NAV_RAIL_WIDTH = 6.5;

const FONT = font.body;
export { FONT };

export const styles: Record<string, React.CSSProperties> = {
  screen: {
    height: '100%',
    background: color.bg,
    overflow: 'hidden',
    padding: `2rem 3rem 2.5rem ${NAV_RAIL_WIDTH + 1.75}rem`,
    boxSizing: 'border-box',
    display: 'grid',
    gridTemplateColumns: '16.75rem 1fr',
    gap: '2rem',
    alignItems: 'stretch',
  },
  sidebar: {
    minWidth: 0,
    height: '100%',
    padding: 0,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  sidebarTitle: {
    ...heading('h1'),
    color: color.textPrimary,
    margin: '0 0 0.25rem',
  },
  sidebarSubtitle: {
    color: color.textFaint,
    fontSize: fontSize.micro,
    margin: '0 0 1.125rem 1px',
    fontFamily: FONT,
    lineHeight: 1.35,
    fontWeight: 500,
    textTransform: 'uppercase',
    letterSpacing: '0.09em',
  },
  content: {
    minWidth: 0,
    height: '100%',
    overflowY: 'auto',
    padding: '0 0.625rem 6rem 0',
    scrollbarWidth: 'thin',
    scrollbarColor: `${color.line} transparent`,
  },
  contentInner: {
    width: '100%',
    maxWidth: layout.reading,
  },
  categoryCard: {
    width: '100%',
  },
  categoryIcon: {
    width: '2.25rem',
    height: '2.25rem',
    borderRadius: radius.md,
    background: color.fill,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  categoryLabel: {
    display: 'block',
    color: color.textStrong,
    fontSize: fontSize.md,
    fontWeight: 600,
    lineHeight: 1.2,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontFamily: FONT,
  },
  categorySubtitle: {
    display: 'block',
    color: color.textDim,
    fontSize: fontSize.xs,
    lineHeight: '0.9375rem',
    fontWeight: 400,
    marginTop: '0.125rem',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontFamily: FONT,
  },
  chevronIcon: {
    display: 'flex',
    color: color.textFaint,
    flexShrink: 0,
  },
  mobileDivider: {
    height: 1,
    background: color.line,
    marginLeft: '3.625rem',
  },
  versionFooter: {
    color: color.textFaint,
    fontSize: fontSize.xs,
    fontWeight: 400,
    fontFamily: FONT,
    textAlign: 'center',
    margin: '0.875rem 0 0',
    letterSpacing: '0.04em',
  },
  detailHeader: {
    display: 'flex',
    alignItems: 'center',
    minHeight: '2.75rem',
    marginBottom: '1.75rem',
    paddingBottom: '1.25rem',
    borderBottom: `1px solid ${color.line}`,
  },
  detailTitle: {
    ...heading('h1'),
    color: color.textPrimary,
  },
  settingsGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.5rem',
    marginBottom: '1.5rem',
  },
  groupHeading: {
    display: 'flex',
    alignItems: 'baseline',
    gap: '0.5rem',
    paddingLeft: '0.25rem',
  },
  groupTitle: {
    color: color.textDim,
    fontSize: fontSize.xs,
    fontWeight: 700,
    margin: 0,
    fontFamily: FONT,
    textTransform: 'uppercase',
    letterSpacing: '0.1em',
  },
  groupSubtitle: {
    color: color.textFaint,
    fontSize: fontSize.xs,
    fontWeight: 400,
    margin: '0.1875rem 0 0',
    fontFamily: FONT,
    lineHeight: '0.9375rem',
  },
  settingsCard: {
    width: '100%',
    borderRadius: radius.lg,
    background: color.surface,
    boxSizing: 'border-box',
  },
  rowTitle: {
    color: color.textStrong,
    fontSize: fontSize.md,
    fontWeight: 600,
    margin: '0 0 0.125rem',
    fontFamily: FONT,
    lineHeight: 1.25,
  },
  rowSubtitle: {
    color: color.textDim,
    fontSize: fontSize.sm,
    margin: 0,
    fontFamily: FONT,
    lineHeight: '0.9375rem',
    fontWeight: 400,
  },
  rowIcon: {
    width: '2.375rem',
    height: '2.375rem',
    borderRadius: radius.md,
    background: color.fill,
    color: 'var(--primary-accent-color)',
    flexShrink: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dropdownWrap: {
    position: 'relative',
    flexShrink: 0,
    minWidth: '10.9375rem',
    zIndex: 2,
  },
  dropdownButton: {
    width: '100%',
    height: '2.25rem',
    border: `1px solid ${color.lineStrong}`,
    borderRadius: radius.md,
    color: color.textPrimary,
    fontSize: fontSize.base,
    fontWeight: 500,
    fontFamily: FONT,
    padding: '0 0.625rem 0 0.75rem',
    outline: 'none',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '0.5rem',
    transition: 'background 0.12s, border-color 0.12s',
  },
  dropdownValue: {
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  dropdownIcon: {
    color: color.outline,
    display: 'flex',
    flexShrink: 0,
    transition: 'transform 0.14s',
  },
  dropdownItem: {
    width: '100%',
    minHeight: '2rem',
    border: 'none',
    borderRadius: radius.sm,
    padding: '0.4375rem 0.625rem',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '0.5rem',
    fontSize: fontSize.base,
    fontWeight: 500,
    fontFamily: FONT,
    textAlign: 'left',
  },
  dropdownItemLabel: {
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
};
