import type React from 'react';

export const NAV_RAIL_WIDTH = 104;

export const styles: Record<string, React.CSSProperties> = {
  screen: {
    height: '100%',
    background: 'linear-gradient(to bottom, #101010 0%, #0C0C0D 52%, #080808 100%)',
    overflow: 'hidden',
    padding: `30px 42px 42px ${NAV_RAIL_WIDTH + 28}px`,
    boxSizing: 'border-box',
    display: 'grid',
    gridTemplateColumns: 'minmax(320px, 380px) 1fr',
    gap: 28,
    alignItems: 'stretch',
  },
  sidebar: {
    minWidth: 0,
    height: '100%',
    padding: 0,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  sidebarTitle: {
    color: '#FFFFFF',
    fontSize: 30,
    fontWeight: 900,
    margin: '0 0 8px',
    fontFamily: 'sans-serif',
    lineHeight: 1,
  },
  sidebarSubtitle: {
    color: 'rgba(255,255,255,0.42)',
    fontSize: 11,
    margin: '0 0 0 4px',
    fontFamily: 'sans-serif',
    lineHeight: 1.35,
    fontWeight: 900,
    textTransform: 'uppercase',
  },
  content: {
    minWidth: 0,
    height: '100%',
    overflowY: 'auto',
    padding: '0 10px 96px 0',
    scrollbarWidth: 'thin',
    scrollbarColor: 'rgba(255,255,255,0.16) transparent',
  },
  categoryCard: {
    width: '100%',
    borderRadius: 18,
    background: '#181818',
    border: '1px solid rgba(255,255,255,0.05)',
    overflow: 'hidden',
    boxSizing: 'border-box',
  },
  categoryIcon: {
    width: 42,
    height: 42,
    borderRadius: 10,
    background: 'rgba(255,255,255,0.08)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  categoryLabel: {
    display: 'block',
    color: 'rgba(255,255,255,0.90)',
    fontSize: 18,
    fontWeight: 800,
    lineHeight: 1.15,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  categorySubtitle: {
    display: 'block',
    color: 'rgba(255,255,255,0.52)',
    fontSize: 13,
    lineHeight: '17px',
    fontWeight: 500,
    marginTop: 3,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  chevronIcon: {
    display: 'flex',
    color: 'rgba(255,255,255,0.38)',
    flexShrink: 0,
  },
  mobileDivider: {
    height: 1,
    background: 'rgba(255,255,255,0.055)',
    marginLeft: 72,
  },
  versionFooter: {
    color: 'rgba(255,255,255,0.42)',
    fontSize: 12,
    fontWeight: 500,
    fontFamily: 'sans-serif',
    textAlign: 'center',
    margin: '14px 0 0',
  },
  detailHeader: {
    display: 'flex',
    alignItems: 'center',
    minHeight: 42,
    marginBottom: 22,
  },
  detailTitle: {
    color: '#FFFFFF',
    fontSize: 30,
    fontWeight: 900,
    margin: 0,
    fontFamily: 'sans-serif',
    lineHeight: 1,
  },
  settingsGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: 7,
    marginBottom: 14,
  },
  groupHeading: {
    paddingLeft: 4,
  },
  groupTitle: {
    color: 'rgba(255,255,255,0.42)',
    fontSize: 10,
    fontWeight: 900,
    margin: 0,
    fontFamily: 'sans-serif',
    textTransform: 'uppercase',
    letterSpacing: 0,
  },
  groupSubtitle: {
    color: 'rgba(255,255,255,0.34)',
    fontSize: 11,
    fontWeight: 500,
    margin: '3px 0 0',
    fontFamily: 'sans-serif',
    lineHeight: '15px',
  },
  settingsCard: {
    width: '100%',
    borderRadius: 18,
    background: '#181818',
    border: '1px solid rgba(255,255,255,0.05)',
    overflow: 'visible',
    boxSizing: 'border-box',
  },
  rowTitle: {
    color: 'rgba(255,255,255,0.90)',
    fontSize: 15,
    fontWeight: 800,
    margin: '0 0 3px',
    fontFamily: 'sans-serif',
    lineHeight: 1.25,
  },
  rowSubtitle: {
    color: 'rgba(255,255,255,0.44)',
    fontSize: 12,
    margin: 0,
    fontFamily: 'sans-serif',
    lineHeight: '15px',
  },
  rowIcon: {
    width: 42,
    height: 42,
    borderRadius: 10,
    background: 'rgba(255,255,255,0.08)',
    color: 'var(--primary-accent-color)',
    flexShrink: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dropdownWrap: {
    position: 'relative',
    flexShrink: 0,
    minWidth: 190,
    zIndex: 2,
  },
  dropdownButton: {
    width: '100%',
    height: 38,
    border: '1px solid rgba(255,255,255,0.10)',
    borderRadius: 999,
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: 800,
    fontFamily: 'sans-serif',
    padding: '0 10px 0 14px',
    outline: 'none',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    transition: 'background 0.12s, border-color 0.12s',
  },
  dropdownValue: {
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  dropdownIcon: {
    color: 'rgba(255,255,255,0.55)',
    display: 'flex',
    flexShrink: 0,
    transition: 'transform 0.14s',
  },
  dropdownMenu: {
    position: 'absolute',
    top: 'calc(100% + 6px)',
    left: 0,
    right: 0,
    maxHeight: 260,
    overflowY: 'auto',
    padding: 5,
    borderRadius: 14,
    background: '#181818',
    border: '1px solid rgba(255,255,255,0.14)',
    boxShadow: '0 22px 70px rgba(0,0,0,0.72)',
    zIndex: 30,
    scrollbarWidth: 'thin',
    scrollbarColor: 'rgba(255,255,255,0.16) transparent',
  },
  dropdownItem: {
    width: '100%',
    minHeight: 34,
    border: 'none',
    borderRadius: 10,
    padding: '8px 10px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    fontSize: 12,
    fontWeight: 750,
    fontFamily: 'sans-serif',
    textAlign: 'left',
  },
  dropdownItemLabel: {
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
};
