export type Tab = 'account' | 'general' | 'appearance' | 'playback' | 'shortcuts' | 'content' | 'addons' | 'plugins' | 'downloads';

export interface Prefs {
  language: string;
  startPage: string;
  backgroundPlayback: boolean;
  alertNewEpisodes: boolean;
  tmdbApiKey: string;
  tmdbPreferOverAddons: boolean;
  tmdbCastImagesEnabled: boolean;
  tmdbSimilarResultsEnabled: boolean;
  tmdbTrailersEnabled: boolean;
  tmdbRecommendationsEnabled: boolean;
  tmdbCollectionInfoEnabled: boolean;
  tmdbEpisodeImagesEnabled: boolean;
  tmdbRatingsEnabled: boolean;
  tmdbEnrichArtworkEnabled: boolean;
  tmdbEnrichDescriptionEnabled: boolean;
  tmdbEnrichGenresKeywordsEnabled: boolean;
  tmdbEnrichCastCrewEnabled: boolean;
  tmdbEnrichNetworkEnabled: boolean;
  tmdbEnrichStatusScheduleEnabled: boolean;
  tmdbEnrichOriginTitlesEnabled: boolean;
  tmdbEnrichWatchProvidersEnabled: boolean;
  rpdbApiKey: string;
  omdbApiKey: string;
  mdblistApiKey: string;
  fanartApiKey: string;
  accentColorArgb: string;
  uiScale: string;
  animationsEnabled: boolean;
  reducedEffects: boolean;
  gifAutoplayEnabled: boolean;
  cardCornerPreset: string;
  navLayout: string;
  navBarPosition: string;
  navItemsAlign: string;
  navSidebarMode: string;
  interfaceDensity: string;
  posterWidthPreset: string;
  posterLandscapeMode: boolean;
  posterHideTitles: boolean;
  cardLayout: string;
  continueWatchingLayout: string;
  continueWatchingArtwork: string;
  continueWatchingRemainingFormat: string;
  continueWatchingProgressDirection: string;
  continueWatchingEnabled: boolean;
  continueWatchingKeepScheduled: boolean;
  continueWatchingShowThisWeek: boolean;
  trailerOnHero: boolean;
  blurUnwatchedEpisodes: boolean;
  spoilerHideEpisodeInfo: boolean;
  continueWatchingHideTitles: boolean;
  showHeroSection: boolean;
  homeHeroAutoplayTrailer: boolean;
  homeHeroAutoplayTrailerDelaySecs: string;
  detailHeroAutoplayTrailer: boolean;
  detailHeroAutoplayTrailerDelaySecs: string;
  heroFeedToggles: string[];
  homeFeedToggles: string[];
  topTenFeedToggles: string[];
  preferredPlayer: string;
  mpvCustomOptions: string;
  animeUpscalingMode: string;
  animeUpscalingQuality: string;
  animeUpscalingModePreset: string;
  frameInterpolationMode: string;
  streamSourceSelectionMode: string;
  streamSourceRegexPattern: string;
  autoRetryNextSource: boolean;
  autoPlayNextEpisode: boolean;
  autoPlayCountdownSecs: string;
  tryBingeGroup: boolean;
  nextEpisodeThresholdPercent: string;
  watchedThresholdPercent: string;
  playbackSpeed: string;
  seekSeconds: string;
  holdToSpeedEnabled: boolean;
  holdSpeed: string;
  stableVolume: boolean;
  playerBufferCacheMb: string;
  playerForwardBufferSeconds: string;
  playerBackBufferSeconds: string;
  autoSkipIntro: boolean;
  useSkipSegments: boolean;
  useAnimeSkip: boolean;
  useChapterSkip: boolean;
  introDbSubmitEnabled: boolean;
  introDbApiKey: string;
  skipDbSubmitEnabled: boolean;
  skipDbApiKey: string;
  theIntroDbSubmitEnabled: boolean;
  theIntroDbApiKey: string;
  animeSkipClientId: string;
  preferredAudioLanguage: string;
  secondaryAudioLanguage: string;
  animePreferJapaneseAudio: boolean;
  preferredSubtitleLanguage: string;
  secondarySubtitleLanguage: string;
  autoEnableSubtitles: boolean;
  subtitlePosition: string;
  subtitleSize: string;
  subtitleColor: string;
  subtitleTextOpacity: string;
  subtitleBackgroundColor: string;
  subtitleBackgroundOpacity: string;
  subtitleOutlineColor: string;
  subtitleOutlineOpacity: string;
  subtitleOutlineSize: string;
  subtitleBold: boolean;
  subtitleForceStyle: boolean;
  subtitleCharacterEdge: string;
  subtitleFont: string;
  downloadSourceSelectionMode: string;
  downloadSourceRegexPattern: string;
  downloadSubtitleLanguage: string;
  downloadDir: string;
  homeSeasonPostersOnHero: boolean;
  detailSeasonPostersOnHero: boolean;
  detailSeasonSelectorMode: string;
  episodeCardsLayout: string;
  heroFeedOrder: string[];
  homeFeedOrder: string[];
  pictureInPicture: boolean;
  notificationsEnabled: boolean;
  automaticUpdates: boolean;
  timezoneConversionEnabled: boolean;
  reduceMotion: boolean;
  subtitleShadow: boolean;
  seekThumbnailEnabled: boolean;
  p2pEnabled: boolean;
  discordRichPresenceEnabled: boolean;
  diagnosticMode: boolean;
  continueWatchingSource: string;
  syncCwSourceOfTruth: string;
  syncCwRanking: string;
  similarTitlesSource: string;
  integrationLibrarySource: string;
  watchProgressSource: string;
  continueWatchingDays: string;
  traktCommentsEnabled: boolean;
  searchSuggestionsOpenDetail: boolean;
  renderBackend: string;
  hdrEnabled: boolean;
  hdrDetectionCompleted: boolean;
  playerEngine: string;
}

export interface TraktTokenResponse {
  access_token: string;
  refresh_token: string;
  expires_in: number;
  created_at: number;
}

export interface SyncMeta {
  lastSyncAt: number;
  continueWatchingCount: number;
  watchlistCount: number;
  watchedCount?: number;
  error?: string;
}

export const DEFAULT_PREFS: Prefs = {
  language: 'en',
  startPage: 'home',
  backgroundPlayback: false,
  alertNewEpisodes: true,
  tmdbApiKey: '',
  tmdbPreferOverAddons: false,
  tmdbCastImagesEnabled: true,
  tmdbSimilarResultsEnabled: true,
  tmdbTrailersEnabled: true,
  tmdbRecommendationsEnabled: true,
  tmdbCollectionInfoEnabled: true,
  tmdbEpisodeImagesEnabled: true,
  tmdbRatingsEnabled: true,
  tmdbEnrichArtworkEnabled: true,
  tmdbEnrichDescriptionEnabled: true,
  tmdbEnrichGenresKeywordsEnabled: true,
  tmdbEnrichCastCrewEnabled: true,
  tmdbEnrichNetworkEnabled: true,
  tmdbEnrichStatusScheduleEnabled: true,
  tmdbEnrichOriginTitlesEnabled: true,
  tmdbEnrichWatchProvidersEnabled: true,
  accentColorArgb: '#FFFFFF',
  uiScale: '100',
  animationsEnabled: true,
  reducedEffects: false,
  gifAutoplayEnabled: false,
  navLayout: 'sidebar',
  navBarPosition: 'left',
  navItemsAlign: 'center',
  navSidebarMode: 'hover',
  cardCornerPreset: 'soft',
  interfaceDensity: 'medium',
  posterWidthPreset: 'medium',
  posterLandscapeMode: false,
  posterHideTitles: false,
  cardLayout: 'vertical',
  continueWatchingLayout: 'horizontal',
  continueWatchingArtwork: 'episode',
  continueWatchingRemainingFormat: 'time',
  continueWatchingProgressDirection: 'remaining',
  continueWatchingEnabled: true,
  continueWatchingKeepScheduled: false,
  continueWatchingShowThisWeek: true,
  trailerOnHero: false,
  blurUnwatchedEpisodes: false,
  spoilerHideEpisodeInfo: false,
  continueWatchingHideTitles: false,
  showHeroSection: true,
  homeHeroAutoplayTrailer: false,
  homeHeroAutoplayTrailerDelaySecs: '2',
  detailHeroAutoplayTrailer: false,
  detailHeroAutoplayTrailerDelaySecs: '2',
  heroFeedToggles: [],
  homeFeedToggles: [],
  topTenFeedToggles: [],
  preferredPlayer: 'mpv',
  mpvCustomOptions: '',
  animeUpscalingMode: 'off',
  animeUpscalingQuality: 'anime4k_m',
  animeUpscalingModePreset: 'a',
  frameInterpolationMode: 'off',
  streamSourceSelectionMode: 'manual',
  streamSourceRegexPattern: '',
  autoRetryNextSource: false,
  autoPlayNextEpisode: true,
  autoPlayCountdownSecs: '7',
  tryBingeGroup: false,
  nextEpisodeThresholdPercent: '85',
  watchedThresholdPercent: '90',
  playbackSpeed: '1.0',
  seekSeconds: '10',
  holdToSpeedEnabled: true,
  holdSpeed: '2.0',
  stableVolume: false,
  playerBufferCacheMb: '100',
  playerForwardBufferSeconds: '60',
  playerBackBufferSeconds: '15',
  autoSkipIntro: false,
  useSkipSegments: true,
  useAnimeSkip: false,
  useChapterSkip: true,
  introDbSubmitEnabled: false,
  introDbApiKey: '',
  skipDbSubmitEnabled: false,
  skipDbApiKey: '',
  theIntroDbSubmitEnabled: false,
  theIntroDbApiKey: '',
  animeSkipClientId: '',
  preferredAudioLanguage: 'none',
  secondaryAudioLanguage: 'none',
  animePreferJapaneseAudio: false,
  preferredSubtitleLanguage: 'none',
  secondarySubtitleLanguage: 'none',
  autoEnableSubtitles: true,
  subtitlePosition: '100',
  subtitleSize: '100',
  subtitleColor: '#FFFFFF',
  subtitleTextOpacity: '1.0',
  subtitleBackgroundColor: '#000000',
  subtitleBackgroundOpacity: '0.5',
  subtitleOutlineColor: '#000000',
  subtitleOutlineOpacity: '1.0',
  subtitleOutlineSize: '3',
  subtitleBold: false,
  subtitleForceStyle: false,
  subtitleCharacterEdge: 'uniform',
  subtitleFont: 'default',
  downloadSourceSelectionMode: 'first',
  downloadSourceRegexPattern: '',
  downloadSubtitleLanguage: 'preferred',
  downloadDir: '',
  homeSeasonPostersOnHero: true,
  detailSeasonPostersOnHero: true,
  detailSeasonSelectorMode: 'tabs',
  episodeCardsLayout: 'standard',
  heroFeedOrder: [],
  homeFeedOrder: [],
  pictureInPicture: false,
  notificationsEnabled: true,
  automaticUpdates: true,
  timezoneConversionEnabled: true,
  reduceMotion: false,
  subtitleShadow: false,
  seekThumbnailEnabled: false,
  p2pEnabled: true,
  discordRichPresenceEnabled: true,
  diagnosticMode: false,
  rpdbApiKey: '',
  omdbApiKey: '',
  mdblistApiKey: '',
  fanartApiKey: '',
  continueWatchingSource: 'local',
  syncCwSourceOfTruth: '',
  syncCwRanking: 'last_watched',
  similarTitlesSource: 'auto',
  integrationLibrarySource: 'local',
  watchProgressSource: 'all',
  continueWatchingDays: '0',
  traktCommentsEnabled: false,
  searchSuggestionsOpenDetail: false,
  renderBackend: 'opengl',
  hdrEnabled: false,
  hdrDetectionCompleted: false,
  playerEngine: 'mpv',
};
